training the models and saving them into the folders

In [2]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 500)

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib.pylab import rcParams
import seaborn as sns
rcParams['figure.figsize']=8,5

In [4]:
data_folder = '../data/raw/'

In [5]:
!ls $data_folder

sample_solution.csv  test.csv  train.csv

In [6]:
train_csv = 'train.csv'
test_csv = 'test.csv'
data_folder+train_csv, data_folder+test_csv

('../data/raw/train.csv', '../data/raw/test.csv')

In [7]:
train_df = pd.read_csv(data_folder+train_csv)
test_df = pd.read_csv(data_folder+test_csv)

train_df.shape, test_df.shape

((2000, 65), (500, 56))

# Unique value per column

In [8]:
def unique_values(df):
    for col in df.columns:
        print(f'---------{col}\n')
        print(df[col].unique())
        print(f'---------END OF SECTION \n')

In [9]:
unique_values(train_df)

---------Component1_fraction

[0.21 0.02 0.08 0.25 0.26 0.5  0.22 0.04 0.05 0.13 0.31 0.   0.01 0.24
 0.03 0.33 0.07 0.34 0.06 0.29 0.3  0.11 0.35 0.1  0.23 0.12 0.16 0.2
 0.14 0.17 0.44 0.38 0.41 0.09 0.49 0.32 0.18 0.36 0.45 0.19 0.42 0.28
 0.15 0.43 0.39 0.47 0.37 0.48 0.4  0.46 0.27]
---------END OF SECTION

---------Component2_fraction

[0.   0.33 0.08 0.42 0.16 0.06 0.17 0.07 0.35 0.19 0.04 0.14 0.2  0.26
 0.25 0.5  0.09 0.29 0.28 0.12 0.13 0.22 0.21 0.18 0.24 0.15 0.43 0.27
 0.1  0.32 0.23 0.05 0.02 0.47 0.37 0.34 0.03 0.11 0.46 0.49 0.38 0.36
 0.48 0.31 0.45 0.01 0.3  0.44 0.4  0.41 0.39]
---------END OF SECTION

---------Component3_fraction

[0.42 0.19 0.18 0.   0.08 0.3  0.31 0.41 0.48 0.5  0.15 0.11 0.32 0.34
 0.22 0.02 0.16 0.03 0.04 0.33 0.38 0.26 0.09 0.25 0.13 0.12 0.2  0.1
 0.01 0.37 0.07 0.23 0.4  0.27 0.35 0.46 0.14 0.24 0.17 0.36 0.05 0.44
 0.21 0.28 0.47 0.06 0.43 0.49 0.39 0.29 0.45]
---------END OF SECTION

---------Component4_fraction

[0.25 0.46 0.5  0.07 0.26 0.4  0.33 0.22 0.21 0.16 0.34 0.45 0.31 0.28
 0.48 0.15 0.23 0.36 0.38 0.13 0.24 0.1  0.27 0.32 0.3  0.12 0.19 0.14
 0.29 0.2  0.18 0.41 0.49 0.35 0.42 0.08 0.47 0.44 0.17 0.11 0.05 0.43
 0.37 0.06 0.09 0.39 0.04 0.01 0.03 0.02]
---------END OF SECTION

---------Component5_fraction

[0.12 0.   0.16 0.26 0.22 0.19 0.04 0.1  0.21 0.23 0.14 0.2  0.11 0.03
 0.07 0.13 0.17 0.18 0.24 0.06 0.08 0.25 0.02 0.05 0.15 0.27 0.01 0.09
 0.29 0.28]
---------END OF SECTION

---------Component1_Property1

[-0.02178224 -0.22433918  0.45776297 ...  0.56897796 -0.06745321
  0.28408984]
---------END OF SECTION

---------Component2_Property1

[ 1.98125061  1.14803633  0.24259084 ... -0.19675891  0.32197703
  0.18909886]
---------END OF SECTION

---------Component3_Property1

[ 0.02003562 -1.10784018 -0.92249206 ... -0.64631836 -0.13753526
 -0.83126681]
---------END OF SECTION

---------Component4_Property1

[ 0.14031512  0.1495331   0.90821291 ... -0.98007018  0.23850665
 -1.08447382]
---------END OF SECTION

---------Component5_Property1

[ 1.03202886 -0.3540001   0.97200333 ... -2.82274909  0.01745499
  0.84508741]
---------END OF SECTION

---------Component1_Property2

[-1.22979946 -1.07504117  0.24040428 ... -0.29895459 -0.24977293
  1.19879088]
---------END OF SECTION

---------Component2_Property2

[-0.58027429  0.89283502  2.21000474 ...  1.11686823 -1.32722491
  1.68812692]
---------END OF SECTION

---------Component3_Property2

[ 0.13399804  1.36347342 -2.65241348 ...  0.33366924  0.02717395
 -0.62225661]
---------END OF SECTION

---------Component4_Property2

[ 0.81783518 -1.74368414 -0.593851   ...  1.39457478 -0.08970104
 -0.57528926]
---------END OF SECTION

---------Component5_Property2

[ 0.21611639  1.27314409 -0.67825508 ... -1.05683508  0.51003905
  0.71859097]
---------END OF SECTION

---------Component1_Property3

[-0.39332205 -0.69108398 -0.27062619 ... -0.82724647 -0.95492997
  0.96481148]
---------END OF SECTION

---------Component2_Property3

[ 0.22118929 -0.25561959  1.4340556  ... -0.21262862  1.97860782
 -2.49766353]
---------END OF SECTION

---------Component3_Property3

[ 0.65610358  1.27077598  0.4994054  ...  2.1940832  -1.19051085
 -1.0550232 ]
---------END OF SECTION

---------Component4_Property3

[ 0.07446108 -0.33379821 -0.94167322 ... -1.0981559  -0.3197549
 -0.23499345]
---------END OF SECTION

---------Component5_Property3

[-3.08293754 -2.08652623  1.43789924 ... -0.20521336 -0.17429977
  0.68686457]
---------END OF SECTION

---------Component1_Property4

[-1.76308491e+00 -1.86970948e+00 -3.06288914e+00  7.34976329e-01
 -5.80059975e-01 -9.60861993e-01 -1.09287336e+00 -7.17148702e-01
 -7.12071341e-01  6.98421366e-02  7.40053689e-01 -3.00805161e-01
 -9.91326155e-01  4.44553354e-02  6.28351764e-01  1.33918220e+00
 -2.15503478e-02 -2.72270600e+00  9.52289378e-02  3.93779751e-02
 -2.09412677e-01  8.87297136e-01  8.92374497e-01 -5.64827894e-01
 -1.73871155e-01  1.59305021e+00  5.82655522e-01  7.45131049e-01
 -2.44954199e-01  1.77583518e+00 -7.06993981e-01  2.41458944e-02
  5.31881919e-01  2.12109568e+00  1.06500474e+00  1.30364068e+00
 -1.62599619e+00 -1.13856960e+00  7.29898969e-01 -5.20145093e-02
 -5.95292056e-01  2.06930863e-01  2.98323348e-01 -1.89103236e-01
 -1.02788112e-01 -9.30397832e-01 -6.61297739e-01  7.55285770e-01
 -1.18426584e+00 -1.19949793e+00 -4.58203329e-01 -1.32643193e+00
 -3.82042925e-01  1.49658037e+00 -4.22661807e-01 -9.25320472e-01
  3.99870553e-01  9.88844341e-01 -2.75418360e-01 -1.20457529e+00
 -4.17584447e-01  4.20179994e-01  1.24778971e+00 -3.61733484e-01
  1.22748027e+00  1.28840860e+00 -1.66661507e+00 -1.16903376e+00
  1.81544062e-01  1.16147459e+00  1.03961794e+00 -4.53125969e-01
  4.81108317e-01 -1.30104513e+00  1.45596148e+00  2.37395025e-01
  1.38487844e+00  3.43006149e-02  6.23274403e-01 -1.26550361e+00
 -3.56656124e-01  1.03454058e+00 -1.24519417e+00 -2.29722118e-01
 -5.74982615e-01  1.18178403e+00 -1.41782442e+00  7.04512167e-01
 -1.49906218e+00  1.18686139e+00  2.08555415e+00 -4.02352366e-01
  2.56282602e+00  1.32395012e+00 -7.62844944e-01  9.01515776e-02
  2.17085584e-01  4.95326956e-02 -8.28850627e-01  9.17761298e-01
  1.15538379e-01  4.60798876e-01 -7.42535503e-01 -6.91761900e-01
  1.74029366e+00 -1.58639074e-01  6.33429124e-01 -1.06748656e+00
  8.16214093e-01 -2.85573081e-01 -2.08803597e+00  2.52627105e-01
 -1.46859802e+00 -1.05733184e+00  2.34957689e+00 -3.41424043e-01
  1.08023683e+00 -1.47367538e+00 -9.81171434e-01  1.59812757e+00
  5.67423441e-01  1.96776143e-01  5.06495118e-01  1.35441428e+00
 -2.39876838e-01 -7.23239503e-02  6.47647764e-02 -1.82401324e+00
  4.15102633e-01  6.94357447e-01 -5.24209012e-01  1.07008211e+00
  2.47549745e-01 -8.49160068e-01 -1.91032836e+00  5.72500801e-01
  1.77075782e+00  1.69459742e+00 -7.52690223e-01  1.23763499e+00
 -3.21114602e-01 -5.19131652e-01 -3.16037242e-01 -6.20678857e-01
  6.02964963e-01  4.04947913e-01 -2.14490037e-01 -1.94180596e-01
  5.87732882e-01  2.67859186e-01  6.89280087e-01  5.16649838e-01
  1.86621422e-01  1.46103884e+00  1.24271235e+00 -2.70341000e-01
  1.66921061e+00 -1.17411112e+00 -8.59314789e-01 -1.24011681e+00
 -1.60060938e+00 -1.66153771e+00  3.54174310e-01  3.84638472e-01
  1.37980108e+00  1.57274077e+00 -1.88494156e+00 -2.48407007e+00
 -2.18450581e+00 -1.03194504e+00 -6.86684540e-01  4.35412074e-01
  3.03400708e-01 -2.83440792e+00 -1.17918848e+00 -6.96839261e-01
 -7.22226062e-01 -5.14054292e-01 -6.30833577e-01 -1.35181873e+00
  1.87738238e+00  1.00306298e-01 -8.74546869e-01  6.63893285e-01
 -2.65263640e-01  4.65876236e-01 -6.51143018e-01  1.31379540e+00
  1.40925180e-01 -1.12333752e+00  8.26368813e-01  3.89715832e-01
 -1.25534889e+00  6.79125366e-01  2.47143353e+00 -8.64392149e-01
 -2.66277081e-02  9.93921701e-01 -1.31627721e+00  1.34933692e+00
  2.38004105e+00  7.24821608e-01 -1.94079252e+00 -1.18020193e-01
 -5.90214695e-01  2.07032207e+00  1.25693099e-01 -1.22996209e+00
 -2.02710765e+00  7.50208410e-01 -1.33252273e-01  2.01447111e+00
 -3.97275006e-01 -6.25756217e-01 -7.57767584e-01  7.60363130e-01
 -1.63716435e-01 -9.71016714e-01 -8.24786708e-02 -7.27303422e-01
 -6.00369416e-01 -1.99257956e-01  2.27240304e-01 -1.43813386e+00
  5.11572478e-01 -1.56506786e+00 -1.42290178e+00  1.01423114e+00
 -1.12942832e-01 -2.43329646e+00  3.59251671e-01  5.62346081e-01
  3.38942230e-01 -5.29286372e-01  1.66311981e-01 -1.05225448e+00
  1.71389342e-01  2.83091267e-01  2.57704466e-01  2.93245987e-01
  3.02994316e+00  7.99968571e-02  9.78689621e-01  7.75595211e-01
  8.72065056e-01 -2.34799478e-01 -9.20243111e-01  1.51079901e-01
 -8.13618546e-01  1.13101043e+00 -7.93309105e-01 -1.29089041e+00
  1.01930850e+00  3.33864869e-01  6.84202726e-01 -5.44518453e-01
  1.19701611e+00  2.21248816e+00 -1.30612249e+00  2.17694664e+00
  4.50644155e-01  1.13608779e+00 -2.55108919e-01 -8.94856310e-01
  3.44019590e-01  8.41600894e-01  4.70953596e-01 -8.23773267e-01
 -1.45336594e+00  1.42041996e+00 -1.15380168e+00  1.07515947e+00
  1.49150301e+00 -1.63107355e+00 -3.46501404e-01  7.80672571e-01
 -3.10959882e-01 -3.05882522e-01 -5.70918696e-02 -8.54237428e-01
  6.18197043e-01  8.77142416e-01  1.21224819e+00  7.95904652e-01
  9.07606577e-01 -2.50031559e-01 -2.67700976e+00 -4.98822211e-01
  9.83766981e-01  2.72936546e-01  4.96340397e-01  2.12008224e-01
 -1.61076411e+00  5.21727199e-01  1.00915378e+00 -1.21980737e+00
  1.56157261e-01 -1.10810544e+00  8.56832975e-01 -1.87986420e+00
 -3.67824286e-02  1.10054627e+00  8.11136733e-01  2.78013907e-01
 -3.26191963e-01 -8.79624230e-01 -2.51961159e+00 -9.50707273e-01
  3.94793192e-01 -2.58561727e+00  1.09546891e+00 -6.81607180e-01
 -1.01163560e+00  3.28787509e-01  9.43148099e-01  2.14140512e+00
 -1.01671296e+00  1.68444270e+00 -1.70215659e+00  1.04977266e+00
 -5.59750534e-01 -1.48383010e+00  5.36959279e-01 -8.08541186e-01
 -4.48048609e-01  1.70475214e+00  7.19744248e-01 -5.49595813e-01
  4.91263037e-01 -1.83924532e+00  1.76466702e-01  1.55243133e+00
 -8.89778950e-01 -6.66375099e-01 -3.17050683e-02 -2.38252286e+00
  9.73612261e-01  1.25286707e+00  6.53738565e-01  1.30770460e-01
 -1.27058097e+00  2.22162944e-01  6.58815925e-01  7.14666888e-01
 -1.78948515e-01 -2.00679820e+00 -8.69469509e-01 -1.40259233e+00
 -5.34363733e-01  3.08478068e-01 -6.31826709e-03  5.46100559e-02
 -6.21692298e-02  1.11577835e+00 -1.39243761e+00 -4.42971248e-01
 -2.90650441e-01 -3.51578764e-01  1.05383658e-01  2.42472385e-01
 -4.78512770e-01 -1.04717712e+00  6.38506484e-01  9.12683938e-01
  1.86215030e+00  9.02529217e-01  1.11070099e+00  1.61234621e-01
 -1.37212817e+00  1.61335965e+00  1.14624251e+00  2.86239027e+00
 -1.93063780e+00  1.68952006e+00  1.27317652e+00 -7.32380782e-01
 -4.73435410e-01  3.23710149e-01 -6.46065658e-01  5.47114000e-01
 -1.02686768e+00 -2.24644758e-01 -2.07280389e+00 -2.80495720e-01
 -2.26574358e+00  2.15155984e+00  3.18632789e-01  3.69406391e-01
 -9.65939354e-01  2.32317664e-01  4.25257354e-01 -3.76965565e-01
 -1.07865472e-01  9.27916018e-01  5.01417758e-01  2.92232546e-02
 -5.85137335e-01 -6.15601497e-01  1.39503316e+00 -1.69707923e+00
 -1.96617932e+00  5.42036640e-01 -5.03899571e-01  1.22240291e+00
 -1.07764128e+00  1.45088412e+00 -1.53561714e-01 -8.99933670e-01
 -1.82909060e+00  5.77578161e-01  1.62859173e+00  1.30871804e+00
 -1.75293019e+00 -1.98141140e+00 -1.41274706e+00 -7.01916621e-01
 -1.60568674e+00 -2.95727801e-01 -1.26042625e+00  1.89261447e+00
 -8.44082708e-01  1.52196717e+00  8.50742173e-02 -1.36705081e+00
 -6.40988298e-01 -1.38329634e-01 -4.12507087e-01  6.99434807e-01
 -1.16395640e+00  1.44072940e+00 -1.46352066e+00 -1.03702240e+00
 -1.92556044e+00 -1.68793795e-01 -5.54673174e-01  8.36523534e-01
  1.48134829e+00 -2.13880957e+00 -1.91540572e+00  7.09589528e-01
 -1.47875274e+00  9.98999062e-01  1.88245974e+00  3.74483751e-01
  6.74048006e-01 -1.79862643e+00 -2.04741709e+00 -1.07256392e+00
 -1.32135457e+00 -7.74013105e-02 -2.44345119e+00  1.36964636e+00
 -9.76094074e-01 -1.54475842e+00 -2.09311333e+00 -1.14872432e+00
  5.96874161e-02  1.39911739e-02 -1.74785283e+00  4.86185677e-01
  2.01853503e-01 -1.33658665e+00 -4.32816528e-01  5.97887602e-01
  1.46002540e-01  2.62375434e+00  1.35847820e-01 -2.55515311e+00
 -8.03463826e-01  8.66987695e-01 -2.45360591e+00  1.34425956e+00
  3.64329031e-01 -2.10326805e+00 -1.87478684e+00  9.22838658e-01
 -1.77323963e+00  5.26804559e-01 -9.35475192e-01  3.83645340e-03
 -1.51937162e+00  1.12593307e+00  1.92815599e+00  8.31446174e-01
 -1.39751497e+00 -3.36346683e-01 -1.78339435e+00 -1.44828858e+00
 -1.48484354e-01  1.90685341e-02 -3.71888205e-01 -2.20989261e+00
 -1.24090684e-03  1.27825388e+00  1.26809915e+00 -5.08976932e-01
  1.31887276e+00 -1.11826016e+00 -9.96403515e-01 -8.75560310e-02
  8.06059372e-01  1.15131987e+00 -9.26333913e-02 -5.69905254e-01
 -1.43305650e+00  2.26833912e+00  1.62351437e+00 -4.63280689e-01
 -2.00172084e+00 -2.65162296e+00  2.45112409e+00  1.15639723e+00
  4.30334714e-01  1.17162931e+00 -1.00148088e+00  8.51755615e-01
  3.49096950e-01 -1.72754339e+00  1.79106726e+00 -2.94103249e+00
  4.45566795e-01  6.13119683e-01 -7.78077025e-01 -6.71452459e-01
  1.74537102e+00 -3.92197646e-01  5.57268720e-01 -9.45629913e-01
  2.88168627e-01 -2.04335317e-01  1.61843701e+00  2.10078624e+00
  4.40489435e-01  6.08042323e-01 -2.31651718e+00 -1.64729876e-02
  1.00407642e+00 -4.88667491e-01 -4.18597888e-02  1.90276919e+00
  1.33410484e+00 -7.83154385e-01  5.52191360e-01  1.47119356e+00
  1.37472372e+00 -4.83590130e-01 -4.37893888e-01 -1.85955476e+00
 -1.57014522e+00  1.44580676e+00 -1.18934320e+00 -9.10088391e-01
  7.90827292e-01  4.76030956e-01  7.70517851e-01  1.82153142e+00
  1.73521630e+00  1.25794443e+00  1.05992738e+00  6.43583844e-01
  2.46635617e+00  1.71490686e+00 -1.35689609e+00  2.22772024e+00
 -1.43406994e-01 -1.21473001e+00  2.43589201e+00  1.70982950e+00
 -1.71231131e+00  1.50165773e+00  8.00982012e-01 -3.31269323e-01
 -1.84025876e-01  1.48642565e+00  2.12617304e+00 -9.55784633e-01
 -2.20481525e+00 -1.52444898e+00 -1.09795072e+00  6.68970646e-01
 -2.42314174e+00  1.54227661e+00 -2.13373221e+00 -1.40766970e+00
  1.05485002e+00  1.14116515e+00 -1.77831699e+00  2.16171456e+00
 -9.77107515e-02  2.22264288e+00  1.12085571e+00 -1.33150929e+00
  1.20717083e+00 -2.55007575e+00  1.41534260e+00  1.94338807e+00
 -8.18695907e-01 -2.23020206e+00 -4.68358050e-01  2.73037891e+00
 -1.53460370e+00 -2.16419637e+00 -1.34674137e+00  9.48225459e-01
 -1.02179032e+00 -1.23503945e+00 -1.45844330e+00  2.65421850e+00
  1.54735397e+00 -4.27739168e-01  1.91698783e-01  1.51181245e+00
  1.56258605e+00  9.68534900e-01  1.66413325e+00  7.85749931e-01
 -1.27565833e+00  1.29348596e+00 -1.79354907e+00 -6.72465901e-02
  2.39019577e+00 -1.20965265e+00  7.65440490e-01  9.53302820e-01
 -1.34166401e+00 -1.14364696e+00  3.13555428e-01 -1.19442056e+00
 -1.15887904e+00  1.69967478e+00  6.48661205e-01  1.76568046e+00
  1.65905589e+00 -1.89001892e+00 -2.01187556e+00  1.64890117e+00
 -1.48890746e+00 -1.08779600e+00 -2.17942845e+00  4.10025273e-01
  2.37496369e+00 -2.11342277e+00  1.20209347e+00 -1.59045466e+00
 -1.58537730e+00  8.91381365e-03 -1.12841488e+00 -1.29596777e+00
  2.87762235e+00  1.83168614e+00 -1.31119985e+00  1.86722766e+00
  1.88753710e+00 -1.50413954e+00 -9.05011031e-01  2.39527313e+00
 -8.39005348e-01 -1.80370379e+00  1.19193875e+00 -9.40552552e-01
 -8.84701590e-01 -2.30128510e+00  1.84691822e+00  8.61910335e-01
  8.97451857e-01  1.60828229e+00 -1.28174913e-01 -1.04209976e+00
  1.08531419e+00  1.50673509e+00  1.10461019e-01  1.65397853e+00
  9.63457540e-01  8.46678254e-01  1.20615739e-01 -1.38736025e+00
 -3.66810845e-01  1.60320493e+00  9.38070739e-01  2.59329018e+00
 -1.53968106e+00  1.85199558e+00 -2.02203028e+00  9.58380180e-01
  3.79561112e-01 -2.81409848e+00 -2.29620774e+00 -4.69371491e-02
  9.32993379e-01 -1.23097553e-01  1.64382381e+00  7.49194969e-02
 -3.87120286e-01 -1.37720553e+00 -1.93571516e+00  1.57781813e+00
  1.75552574e+00  1.89769183e+00 -1.86463212e+00 -1.44321122e+00
  1.23255763e+00 -2.53992103e+00 -1.13956273e-02  2.13632776e+00
 -1.97633404e+00  2.02462583e+00  1.32902748e+00 -9.15165751e-01
 -8.33927987e-01 -1.06240920e+00 -2.98672873e+00  1.93831071e+00
 -1.10302808e+00 -1.08271864e+00 -6.05446776e-01 -7.98386466e-01
 -2.41298702e+00  2.21756552e+00  1.43057468e+00  2.51205242e+00
 -2.14896429e+00  1.36456900e+00 -2.08295861e+00 -2.57546255e+00
 -1.80878115e+00 -9.86248795e-01 -7.67922304e-01]
---------END OF SECTION

---------Component2_Property4

[ 9.84514824e-01  8.96234096e-01 -2.78578664e-01 -2.31042888e-01
 -1.07989604e+00  6.63599439e-03  1.69615799e-01 -5.43420847e-01
 -2.10670412e-01 -4.68721770e-01 -1.34473822e+00  6.04228612e-01
 -7.26773128e-01 -8.62589632e-01 -1.69925461e-01  1.35121939e+00
 -3.80441042e-01  7.46835942e-01 -1.97088762e-01  9.03024922e-01
  4.73809456e-02  6.77534212e-02  1.33084691e+00  5.83856137e-01
 -1.83507111e-01  1.42591846e+00 -8.76171282e-01  5.15947885e-01
  8.81258969e-02 -1.56204463e+00  4.07294682e-01  1.43950011e+00
  2.44314877e-01  6.31391913e-01 -1.03236026e+00 -2.05273064e-02
 -7.19982303e-01 -1.12743181e+00 -1.15459512e+00  7.40045117e-01
 -4.75512595e-01 -1.37364812e-02 -1.59599875e+00  3.80131381e-01
  1.95560283e+00  1.14749463e+00  5.70274486e-01 -2.01702992e+00
 -6.31701575e-01  5.36320360e-01 -5.02675896e-01 -2.11210147e+00
 -2.11889230e+00  1.27652031e+00  1.75187807e+00  2.51105702e-01
  2.70084700e-02 -9.78033660e-01  1.99634778e+00  1.34268196e-02
  1.40554599e+00 -1.41943730e+00  8.07953369e-01  8.35116669e-01
 -1.05952356e+00  1.16786710e+00 -6.52074051e-01 -5.23048372e-01
  1.54815332e+00  3.05432303e-01 -7.48539081e-02 -4.95885071e-01
  2.98641478e-01 -5.44814325e-02  4.88784584e-01  1.22080023e-01
 -4.89094246e-01 -3.87231868e-01  9.49167221e-02 -9.37288709e-01
 -2.13247395e+00  8.69070796e-01  5.43111186e-01  2.60073122e+00
  4.05901204e-02  6.38182739e-01  3.52968080e-01 -4.76906073e-02
  1.22219371e+00  1.79941385e+00  1.15428545e+00  6.85718515e-01
  4.61621283e-01 -2.03879587e-01  1.23577536e+00  6.11019438e-01
 -9.52263837e-02  1.00488730e+00 -4.14395168e-01 -1.07310521e+00
  3.73340556e-01 -9.98406136e-01 -1.92874919e+00 -6.99609827e-01
  6.92509340e-01  1.13391298e+00  8.62279970e-01  5.77065312e-01
  1.62824974e-01 -6.92819002e-01  1.59568909e+00  3.12223129e-01
 -1.02017209e-01  4.27667157e-01  6.24601088e-01 -5.63793323e-01
  9.23397397e-01 -6.86028177e-01 -1.47376390e+00  5.63483661e-01
  8.01162543e-01 -1.63134636e-01  1.69076065e+00 -9.30497884e-01
 -1.29180510e-01 -9.91615311e-01  1.20861206e+00  7.67208417e-01
  2.02176448e-02  8.41907495e-01  1.78583220e+00  1.65001569e+00
  5.49902011e-01  2.17151576e-01 -6.65655701e-01 -1.54830815e-04
 -1.35831987e+00  1.20182123e+00 -5.70584148e-01  1.08498372e-01
  2.18649089e+00 -1.10026851e+00 -1.31757492e+00  1.42452499e-01
  4.95575409e-01 -7.40354778e-01  2.71478177e-01 -1.32436575e+00
 -1.43301895e+00 -2.12568312e+00 -2.83192894e+00  1.01167812e+00
 -2.51415363e-01  1.12033133e+00 -1.25645749e+00 -9.50870360e-01
  2.78269003e-01  5.09157060e-01 -1.38548317e+00 -2.58206189e-01
 -9.10125408e-01  7.87580893e-01 -2.09851982e+00 -8.08263030e-01
  3.32595604e-01 -2.85369489e-01 -4.00813518e-01  3.46177255e-01
  2.25439914e+00  3.93713031e-01  1.03205060e+00 -2.71787839e-01
  2.53282297e+00  1.26972948e+00  4.54830458e-01 -8.89752933e-01
  7.26463466e-01 -1.90297937e-01  4.48039633e-01 -2.37833713e-01
 -6.24910750e-01  1.38517351e+00 -1.33794740e+00  3.66549730e-01
  2.57896527e-01 -1.17496759e+00  9.98096474e-01 -5.97747449e-01
 -6.45283225e-01  8.14744194e-01 -2.98951140e-01  1.22898453e+00
 -1.14101347e+00 -3.53277742e-01 -1.42622812e+00 -4.48349294e-01
 -1.33115657e+00  1.29010196e+00 -4.41558469e-01 -8.82962108e-01
  1.05242308e+00 -1.29041162e+00 -5.84165799e-01 -3.41089568e-02
  3.19013954e-01 -1.08668686e+00  2.85059828e-01 -6.18119925e-01
  1.49382671e+00  3.37992952e-02 -4.07604343e-01 -8.69380457e-01
 -4.27976819e-01 -4.21185994e-01 -1.42762160e-01  7.12881816e-01
 -2.00344827e+00 -1.56343811e-01  1.90806705e+00  1.96779100e-01
 -6.04538274e-01  1.01707547e-01  1.45987259e+00 -2.92160315e-01
 -5.77374973e-01  4.68412108e-01  7.73999243e-01  1.07958638e+00
 -7.47145603e-01 -1.08808034e-01  9.30188222e-01 -1.44660060e+00
  1.39196434e+00  9.70933174e-01  2.30733226e-01  8.21535019e-01
  7.94371718e-01  8.82652446e-01 -1.39227400e+00 -3.66859392e-01
  8.13350717e-02  8.28325844e-01  1.55494414e+00  1.75866890e+00
  2.10360751e-01  7.80790068e-01 -8.15053856e-01 -7.74308904e-01
  1.79262302e+00 -1.03915109e+00 -1.23608502e+00 -4.82303420e-01
  1.28870848e-01 -2.17461237e-01  1.09995885e+00 -8.84355585e-02
 -8.55798807e-01  7.33254291e-01 -5.90956624e-01  1.44629094e+00
 -3.60068567e-01 -3.12532790e-01 -1.45339142e+00  4.20876332e-01
 -2.44624538e-01 -1.76576938e+00 -2.17321890e+00  1.18823958e+00
  2.91850653e-01  1.25614783e+00 -5.16257546e-01  1.83197450e-01
 -6.80630829e-02  1.65680652e+00 -1.48055473e+00 -1.02556944e+00
 -1.56883545e+00 -3.94022693e-01  1.01846895e+00 -4.08997820e-02

# Checking null values and dealing with it

In [10]:
print(train_df.isnull().count())

Component1_fraction      2000
Component2_fraction      2000
Component3_fraction      2000
Component4_fraction      2000
Component5_fraction      2000
Component1_Property1     2000
Component2_Property1     2000
Component3_Property1     2000
Component4_Property1     2000
Component5_Property1     2000
Component1_Property2     2000
Component2_Property2     2000
Component3_Property2     2000
Component4_Property2     2000
Component5_Property2     2000
Component1_Property3     2000
Component2_Property3     2000
Component3_Property3     2000
Component4_Property3     2000
Component5_Property3     2000
Component1_Property4     2000
Component2_Property4     2000
Component3_Property4     2000
Component4_Property4     2000
Component5_Property4     2000
Component1_Property5     2000
Component2_Property5     2000
Component3_Property5     2000
Component4_Property5     2000
Component5_Property5     2000
Component1_Property6     2000
Component2_Property6     2000
Component3_Property6     2000
Component4_Property6     2000
Component5_Property6     2000
Component1_Property7     2000
Component2_Property7     2000
Component3_Property7     2000
Component4_Property7     2000
Component5_Property7     2000
Component1_Property8     2000
Component2_Property8     2000
Component3_Property8     2000
Component4_Property8     2000
Component5_Property8     2000
Component1_Property9     2000
Component2_Property9     2000
Component3_Property9     2000
Component4_Property9     2000
Component5_Property9     2000
Component1_Property10    2000
Component2_Property10    2000
Component3_Property10    2000
Component4_Property10    2000
Component5_Property10    2000
BlendProperty1           2000
BlendProperty2           2000
BlendProperty3           2000
BlendProperty4           2000
BlendProperty5           2000
BlendProperty6           2000
BlendProperty7           2000
BlendProperty8           2000
BlendProperty9           2000
BlendProperty10          2000
dtype: int64

In [11]:
# type(train_df.isnull().count())
count_series = train_df.isnull().count()

In [12]:
count_series.iloc[0]

np.int64(2000)

In [13]:
count_series.index

Index(['Component1_fraction', 'Component2_fraction', 'Component3_fraction',
       'Component4_fraction', 'Component5_fraction', 'Component1_Property1',
       'Component2_Property1', 'Component3_Property1', 'Component4_Property1',
       'Component5_Property1', 'Component1_Property2', 'Component2_Property2',
       'Component3_Property2', 'Component4_Property2', 'Component5_Property2',
       'Component1_Property3', 'Component2_Property3', 'Component3_Property3',
       'Component4_Property3', 'Component5_Property3', 'Component1_Property4',
       'Component2_Property4', 'Component3_Property4', 'Component4_Property4',
       'Component5_Property4', 'Component1_Property5', 'Component2_Property5',
       'Component3_Property5', 'Component4_Property5', 'Component5_Property5',
       'Component1_Property6', 'Component2_Property6', 'Component3_Property6',
       'Component4_Property6', 'Component5_Property6', 'Component1_Property7',
       'Component2_Property7', 'Component3_Property7', 'Component4_Property7',
       'Component5_Property7', 'Component1_Property8', 'Component2_Property8',
       'Component3_Property8', 'Component4_Property8', 'Component5_Property8',
       'Component1_Property9', 'Component2_Property9', 'Component3_Property9',
       'Component4_Property9', 'Component5_Property9', 'Component1_Property10',
       'Component2_Property10', 'Component3_Property10',
       'Component4_Property10', 'Component5_Property10', 'BlendProperty1',
       'BlendProperty2', 'BlendProperty3', 'BlendProperty4', 'BlendProperty5',
       'BlendProperty6', 'BlendProperty7', 'BlendProperty8', 'BlendProperty9',
       'BlendProperty10'],
      dtype='object')

In [14]:
for idx in range(len(count_series.index)):
    if count_series.iloc[idx] !=2000:
        print(idx, count_series.iloc[idx])
    # break
# Because it doesn't print anything so every columns has som values.

In [15]:
row_check = train_df.isnull().any(axis=1)

In [16]:
for idx in range(len(row_check.index)):
    if row_check.iloc[idx] == True:
        print(idx, count_series.iloc[idx])
    # break
# Because it doesn't print anything so every row has some values ie no null values as such.

# Data preparation

In [17]:
train_df.columns

Index(['Component1_fraction', 'Component2_fraction', 'Component3_fraction',
       'Component4_fraction', 'Component5_fraction', 'Component1_Property1',
       'Component2_Property1', 'Component3_Property1', 'Component4_Property1',
       'Component5_Property1', 'Component1_Property2', 'Component2_Property2',
       'Component3_Property2', 'Component4_Property2', 'Component5_Property2',
       'Component1_Property3', 'Component2_Property3', 'Component3_Property3',
       'Component4_Property3', 'Component5_Property3', 'Component1_Property4',
       'Component2_Property4', 'Component3_Property4', 'Component4_Property4',
       'Component5_Property4', 'Component1_Property5', 'Component2_Property5',
       'Component3_Property5', 'Component4_Property5', 'Component5_Property5',
       'Component1_Property6', 'Component2_Property6', 'Component3_Property6',
       'Component4_Property6', 'Component5_Property6', 'Component1_Property7',
       'Component2_Property7', 'Component3_Property7', 'Component4_Property7',
       'Component5_Property7', 'Component1_Property8', 'Component2_Property8',
       'Component3_Property8', 'Component4_Property8', 'Component5_Property8',
       'Component1_Property9', 'Component2_Property9', 'Component3_Property9',
       'Component4_Property9', 'Component5_Property9', 'Component1_Property10',
       'Component2_Property10', 'Component3_Property10',
       'Component4_Property10', 'Component5_Property10', 'BlendProperty1',
       'BlendProperty2', 'BlendProperty3', 'BlendProperty4', 'BlendProperty5',
       'BlendProperty6', 'BlendProperty7', 'BlendProperty8', 'BlendProperty9',
       'BlendProperty10'],
      dtype='object')

## 1. Multiply each ComponentX_fraction with its respective properties

In [18]:
for comp_num in range(1, 6):  # For components 1 through 5
    for prop_num in range(1, 11):  # For properties 1 through 10
        # Original column name
        orig_col = f'Component{comp_num}_Property{prop_num}'
        # New column name
        new_col = f'Fraction{comp_num}_Property{prop_num}'
        # Multiply fraction with property and create new column
        train_df[new_col] = train_df[f'Component{comp_num}_fraction'] * train_df[orig_col]

In [19]:
train_df.head(3).T

                              0         1         2
Component1_fraction    0.210000  0.020000  0.080000
Component2_fraction    0.000000  0.330000  0.080000
Component3_fraction    0.420000  0.190000  0.180000
Component4_fraction    0.250000  0.460000  0.500000
Component5_fraction    0.120000  0.000000  0.160000
Component1_Property1  -0.021782 -0.224339  0.457763
Component2_Property1   1.981251  1.148036  0.242591
Component3_Property1   0.020036 -1.107840 -0.922492
Component4_Property1   0.140315  0.149533  0.908213
Component5_Property1   1.032029 -0.354000  0.972003
Component1_Property2  -1.229799 -1.075041  0.240404
Component2_Property2  -0.580274  0.892835  2.210005
Component3_Property2   0.133998  1.363473 -2.652413
Component4_Property2   0.817835 -1.743684 -0.593851
Component5_Property2   0.216116  1.273144 -0.678255
Component1_Property3  -0.393322 -0.691084 -0.270626
Component2_Property3   0.221189 -0.255620  1.434056
Component3_Property3   0.656104  1.270776  0.499405
Component4_Property3   0.074461 -0.333798 -0.941673
Component5_Property3  -3.082938 -2.086526  1.437899
Component1_Property4  -1.763085 -1.869709 -3.062889
Component2_Property4   0.984515  0.896234 -0.278579
Component3_Property4  -1.548115 -1.541202  0.356307
Component4_Property4  -1.654290 -0.244737  0.480321
Component5_Property4  -1.410049 -0.175381 -0.047104
Component1_Property5   0.051779 -0.375340  0.185845
Component2_Property5   1.005824  1.081967 -0.020313
Component3_Property5  -0.430868 -0.017281 -0.724472
Component4_Property5   1.743608 -1.913700 -2.135805
Component5_Property5   0.296713 -0.436747 -3.052837
Component1_Property6  -1.483333 -0.222145 -1.519468
Component2_Property6  -1.748359  0.344109 -0.102943
Component3_Property6   1.503443  0.703365  0.613740
Component4_Property6   0.023043 -0.737121 -0.591977
Component5_Property6   1.741303  0.988643  1.836633
Component1_Property7  -0.509380 -1.204671  0.020619
Component2_Property7  -0.468733  0.795790  2.045834
Component3_Property7  -1.317675  0.248477 -1.689579
Component4_Property7   0.132155  0.366540 -0.279133
Component5_Property7   0.221237  0.125072 -0.664966
Component1_Property8   0.293815  0.948338 -0.671136
Component2_Property8  -0.115753  0.812621  0.397808
Component3_Property8  -0.917992 -0.574724  2.148911
Component4_Property8  -0.274704 -0.837602 -0.983115
Component5_Property8   0.513326  0.636329  1.039423
Component1_Property9   0.480368 -1.958826 -0.798978
Component2_Property9   1.044967 -0.019603 -0.444027
Component3_Property9  -0.450956 -0.807923  0.148405
Component4_Property9   0.674572  0.148715 -0.793607
Component5_Property9  -0.636394  1.439313  0.123834
Component1_Property10 -1.244963 -1.160435  0.006829
Component2_Property10 -1.355050 -0.014276  0.668734
Component3_Property10 -0.314423 -0.135968  0.015449
Component4_Property10  0.993593 -1.221155 -0.098661
Component5_Property10 -2.728928  0.896222 -0.424314
BlendProperty1         0.489143 -1.257481  1.784349
BlendProperty2         0.607589 -1.475283  0.450467
BlendProperty3         0.321670 -0.437385  0.622687
BlendProperty4        -1.236055 -1.402911  1.375614
BlendProperty5         1.601132  0.147941 -0.428790
BlendProperty6         1.384662 -1.143244  1.161616
BlendProperty7         0.305850 -0.439171  0.601289
BlendProperty8         0.193460 -1.379041  0.872950
BlendProperty9         0.580374 -1.280989  0.660000
BlendProperty10       -0.762738 -0.503625  2.024576
Fraction1_Property1   -0.004574 -0.004487  0.036621
Fraction1_Property2   -0.258258 -0.021501  0.019232
Fraction1_Property3   -0.082598 -0.013822 -0.021650
Fraction1_Property4   -0.370248 -0.037394 -0.245031
Fraction1_Property5    0.010874 -0.007507  0.014868
Fraction1_Property6   -0.311500 -0.004443 -0.121557
Fraction1_Property7   -0.106970 -0.024093  0.001650
Fraction1_Property8    0.061701  0.018967 -0.053691
Fraction1_Property9    0.100877 -0.039177 -0.063918
Fraction1_Property10  -0.261442 -0.023209  0.000546
Fraction2_Property1    0.000000  0.378852  0.019407
Fraction2_Property2   -0.000000  0.294636  0.176800
Fraction2_Property3    0.000000 -0.084354  0.114724
Fraction2_Property4    0.000000  0.295757 -0.022286
Fraction2_Property5    0.000000  0.357049 -0.001625
Fraction2_Property6   -0.000000  0.113556 -0.008235
Fraction2_Property7   -0.000000  0.262611  0.163667
Fraction2_Property8   -0.000000  0.268165  0.031825
Fraction2_Property9    0.000000 -0.006469 -0.035522
Fraction2_Property10  -0.000000 -0.004711  0.053499
Fraction3_Property1    0.008415 -0.210490 -0.166049
Fraction3_Property2    0.056279  0.259060 -0.477434
Fraction3_Property3    0.275564  0.241447  0.089893
Fraction3_Property4   -0.650208 -0.292828  0.064135
Fraction3_Property5   -0.180965 -0.003283 -0.130405
Fraction3_Property6    0.631446  0.133639  0.110473
Fraction3_Property7   -0.553424  0.047211 -0.304124
Fraction3_Property8   -0.385556 -0.109198  0.386804
Fraction3_Property9   -0.189401 -0.153505  0.026713
Fraction3_Property10  -0.132058 -0.025834  0.002781
Fraction4_Property1    0.035079  0.068785  0.454106
Fraction4_Property2    0.204459 -0.802095 -0.296925
Fraction4_Property3    0.018615 -0.153547 -0.470837
Fraction4_Property4   -0.413572 -0.112579  0.240160
Fraction4_Property5    0.435902 -0.880302 -1.067902
Fraction4_Property6    0.005761 -0.339076 -0.295989
Fraction4_Property7    0.033039  0.168608 -0.139566
Fraction4_Property8   -0.068676 -0.385297 -0.491557
Fraction4_Property9    0.168643  0.068409 -0.396804
Fraction4_Property10   0.248398 -0.561731 -0.049330
Fraction5_Property1    0.123843 -0.000000  0.155521
Fraction5_Property2    0.025934  0.000000 -0.108521
Fraction5_Property3   -0.369953 -0.000000  0.230064
Fraction5_Property4   -0.169206 -0.000000 -0.007537
Fraction5_Property5    0.035606 -0.000000 -0.488454
Fraction5_Property6    0.208956  0.000000  0.293861
Fraction5_Property7    0.026548  0.000000 -0.106395
Fraction5_Property8    0.061599  0.000000  0.166308
Fraction5_Property9   -0.076367  0.000000  0.019813
Fraction5_Property10  -0.327471  0.000000 -0.067890

In [20]:
cols_to_drop = [f'Component{comp_num}_Property{prop_num}' 
                for comp_num in range(1, 6) 
                for prop_num in range(1, 11)]

In [21]:
train_df = train_df.drop(columns=cols_to_drop)

In [22]:
train_df.shape

(2000, 65)

## 2. Calculate sum of all 5 component fractions

This can only be used for cheking if the fraction sum to 1. This is not a very important feature to deal with.

In [23]:
train_df['Total_Fraction'] = (train_df['Component1_fraction'] + 
                             train_df['Component2_fraction'] + 
                             train_df['Component3_fraction'] + 
                             train_df['Component4_fraction'] + 
                             train_df['Component5_fraction'])

In [24]:
are_all_ones_cola = (train_df['Total_Fraction'] == 1).all()
print(f"Are all values in 'Total_Fraction' equal to 1? {are_all_ones_cola}")

Are all values in 'Total_Fraction' equal to 1? False

In [29]:
(train_df['Total_Fraction'] == 1).value_counts()

Total_Fraction
True     1756
False     244
Name: count, dtype: int64

In [42]:
train_df[train_df['Total_Fraction'] != 1]

,Component1_fraction,Component2_fraction,Component3_fraction,Component4_fraction,Component5_fraction,BlendProperty1,BlendProperty2,BlendProperty3,BlendProperty4,BlendProperty5,...,Fraction5_Property2,Fraction5_Property3,Fraction5_Property4,Fraction5_Property5,Fraction5_Property6,Fraction5_Property7,Fraction5_Property8,Fraction5_Property9,Fraction5_Property10,Total_Fraction
9,0.13,0.07,0.48,0.22,0.10,0.152607,0.293616,0.147049,1.313949,-0.082938,...,0.007462,0.143790,0.077921,0.160455,0.023714,0.031496,0.133041,0.033748,-0.057366,1.0
12,0.04,0.35,0.15,0.25,0.21,0.008616,0.166243,-0.228251,0.849653,0.472937,...,-0.299689,-0.257732,-0.035034,0.244701,-0.424962,-0.097334,-0.310471,-0.013858,-0.020123,1.0
16,0.01,0.20,0.34,0.34,0.11,0.174080,-0.319725,0.647143,-0.133350,0.026285,...,0.140046,-0.086697,0.097590,0.190803,-0.353673,0.158755,-0.106713,-0.121878,0.148097,1.0
19,0.50,0.08,0.00,0.31,0.11,0.682523,0.626248,-1.067760,-0.829795,0.303554,...,0.045406,0.158169,-0.024583,0.062128,0.067597,0.200491,-0.049677,0.146999,-0.026702,1.0
22,0.00,0.09,0.48,0.22,0.21,1.978683,2.174204,0.993644,0.824261,-0.446437,...,0.267360,0.301959,-0.203398,-0.336882,0.008994,-0.387072,-0.027780,0.345268,-0.379880,1.0
23,0.03,0.29,0.30,0.15,0.23,0.633492,1.882407,-1.134957,0.650150,-0.564751,...,0.292823,0.231048,-0.154173,0.066361,0.081413,-0.195188,0.162817,0.040250,0.386086,1.0
26,0.07,0.12,0.48,0.23,0.10,-0.377309,-0.021708,0.664742,-0.173251,-0.277588,...,0.121298,0.127836,0.068942,-0.110035,-0.046474,0.083637,-0.035345,0.048645,0.124446,1.0
31,0.34,0.26,0.04,0.15,0.21,0.598538,-0.258877,-1.608995,0.465157,-0.369165,...,0.040241,-0.022808,0.219756,-0.002814,0.143424,0.079887,0.141556,-0.241600,-0.048793,1.0
53,0.50,0.00,0.19,0.21,0.10,-0.766217,-0.592591,-0.303448,-0.996652,1.342579,...,-0.177975,0.049614,0.073325,0.102990,0.156523,0.021051,-0.055142,0.070408,-0.083077,1.0
54,0.00,0.50,0.10,0.30,0.10,-1.624080,-0.400854,-1.819501,-1.700351,-0.483067,...,0.127314,-0.016105,0.119932,0.080547,0.183663,0.090061,0.054174,-0.006825,0.103864,1.0
55,0.29,0.27,0.00,0.34,0.10,-1.190317,-0.374352,-0.434185,-1.007534,0.185240,...,0.112214,-0.229105,0.028321,-0.083663,0.052226,-0.204199,0.062447,0.128988,0.102027,1.0
67,0.44,0.13,0.00,0.33,0.10,-0.320405,-0.765127,0.094022,0.077034,-0.505259,...,0.064773,-0.042796,0.062208,-0.016702,-0.011539,0.179997,-0.141157,0.015602,-0.204770,1.0
80,0.05,0.35,0.24,0.20,0.16,-0.637138,-0.170446,-0.957821,-0.278443,-0.446971,...,-0.332853,0.122705,-0.223213,-0.056084,-0.033914,-0.198420,-0.171064,0.073832,0.160250,1.0
82,0.16,0.02,0.48,0.22,0.12,0.369966,0.537817,0.012654,0.889553,-0.693492,...,-0.095573,0.159100,0.016924,0.099669,0.061969,-0.010630,0.098348,-0.032328,0.128628,1.0
102,0.30,0.03,0.31,0.18,0.18,-0.150884,1.180905,0.995929,0.791616,-0.600044,...,-0.114724,0.025016,0.057327,0.101517,-0.142873,0.183477,0.050863,-0.065999,-0.173301,1.0
105,0.00,0.09,0.50,0.33,0.08,-1.112536,0.928592,1.042099,0.476039,-0.475714,...,-0.036226,-0.027612,0.092696,0.042947,0.125895,-0.015043,0.083614,0.097422,0.108594,1.0
106,0.16,0.32,0.08,0.36,0.08,0.158572,-0.030632,-0.083571,-0.949497,-0.846164,...,0.101852,0.019995,-0.026858,0.044704,0.048102,0.039033,0.014725,0.134962,0.090132,1.0
111,0.18,0.16,0.12,0.46,0.08,0.213448,-0.197760,0.120993,-0.020904,0.364784,...,0.035020,-0.105404,-0.004709,0.053392,-0.049529,-0.003655,0.043061,0.033367,0.138088,1.0
120,0.50,0.00,0.00,0.42,0.08,0.855027,0.341483,0.339270,-0.028158,2.252996,...,0.101718,-0.005332,0.119805,-0.100515,-0.088214,-0.120125,0.048612,0.063576,0.036243,1.0
122,0.36,0.00,0.13,0.41,0.10,0.249237,0.660864,0.664514,-0.097077,0.957557,...,0.119158,0.085082,-0.087556,0.123987,0.087958,-0.043510,0.087693,0.168702,0.081167,1.0
138,0.31,0.26,0.00,0.33,0.10,-0.709312,-1.206743,-0.043115,-0.445300,-1.280785,...,-0.027185,0.019170,-0.066070,-0.038108,-0.154208,0.006194,0.051864,-0.031791,0.023370,1.0
139,0.00,0.50,0.19,0.21,0.10,-1.363417,-1.096948,-1.095873,-1.196154,-1.144824,...,-0.038861,-0.142382,0.008224,-0.145521,0.007720,-0.265225,0.096524,-0.098878,0.046829,1.0
147,0.18,0.48,0.01,0.08,0.25,-0.403793,-0.044965,-1.973552,-0.263934,-0.935468,...,0.089283,-0.089876,-0.000017,-0.559106,0.459158,-0.148721,-0.127111,-0.613072,-0.158574,1.0
176,0.05,0.35,0.17,0.33,0.10,-1.110030,0.207889,-0.263221,-0.652057,-0.275449,...,0.127314,-0.041664,-0.122298,-0.182686,0.004158,0.103041,-0.020743,-0.096737,-0.158407,1.0
179,0.36,0.29,0.00,0.21,0.14,-0.022998,-0.846798,0.107507,-1.308601,-0.130531,...,-0.005633,0.139556,-0.069600,0.240338,-0.160557,-0.000389,-0.105977,0.002343,0.024908,1.0
192,0.03,0.50,0.05,0.32,0.10,-0.293325,-0.790007,-2.106804,-0.481573,0.202486,...,0.127314,-0.110198,0.146015,-0.124320,-0.130294,-0.149925,0.061227,0.019453,-0.147873,1.0
201,0.01,0.38,0.22,0.30,0.09,0.026033,0.531327,-0.690404,-0.278443,-0.803518,...,0.114583,-0.131696,0.082059,0.001729,-0.203338,-0.032544,-0.038346,-0.184204,-0.000423,1.0
202,0.41,0.00,0.15,0.34,0.10,0.026033,0.739289,1.068155,-0.405399,0.943252,...,0.127314,-0.030320,0.013676,-0.045762,0.101802,0.031752,0.057417,-0.113509,-0.063222,1.0
205,0.44,0.14,0.02,0.33,0.07,-0.363948,-1.079910,-0.412015,-1.261446,-0.840817,...,-0.115610,0.100653,-0.116587,-0.010001,0.084399,-0.039244,0.037898,0.052370,-0.009667,1.0
210,0.50,0.11,0.00,0.29,0.10,-0.562935,-0.512543,0.190476,-1.119981,-0.841753,...,-0.049967,0.143790,-0.002359,0.031786,-0.048864,0.156876,-0.008539,0.086289,0.172611,1.0
211,0.50,0.00,0.18,0.19,0.13,-0.930489,-0.050103,0.215160,-0.173251,1.662495,...,0.097776,0.186927,-0.202901,-0.057770,-0.042369,-0.006050,-0.117752,0.107555,-0.055116,1.0
230,0.20,0.00,0.50,0.18,0.12,0.127913,0.105936,0.619258,0.113307,1.363836,...,0.023794,-0.060761,-0.032847,0.036522,0.049008,0.211375,0.133779,0.083168,0.134283,1.0
238,0.00,0.30,0.30,0.31,0.09,-0.325177,-0.840307,0.102251,-1.685842,-0.070104,...,-0.093253,0.021103,0.028375,0.092445,0.036255,0.068198,-0.060887,0.149920,-0.049103,1.0
244,0.19,0.06,0.41,0.10,0.24,0.673695,0.416934,0.286472,1.615016,-0.120638,...,-0.563829,0.004075,-0.077239,0.253561,0.382568,-0.015323,-0.139915,-0.111695,-0.153562,1.0
246,0.00,0.26,0.43,0.21,0.10,-0.900187,-0.241029,-0.132254,-0.282070,-0.189488,...,-0.012751,0.001891,0.003628,0.024419,-0.032505,-0.129814,-0.125248,0.073017,-0.115059,1.0
258,0.00,0.19,0.50,0.08,0.23,1.050912,0.385023,0.190018,1.640408,0.278688,...,-0.242033,-0.328938,0.032684,0.007023,0.230016,0.514772,0.186757,0.006095,-0.026104,1.0
259,0.06,0.29,0.05,0.50,0.10,0.284072,-0.517411,-0.344589,0.174972,0.222940,...,-0.091725,-0.074040,-0.096001,0.081393,0.183663,-0.067520,-0.208804,-0.040134,0.142603,1.0
285,0.09,0.48,0.09,0.08,0.26,0.433670,0.131086,-2.049435,0.305555,-0.461677,...,-0.125400,-0.513074,0.034168,-0.147005,0.131395,-0.026994,-0.093801,-0.026195,-0.252486,1.0
286,0.38,0.04,0.00,0.50,0.08,0.769371,0.053472,0.837078,-0.006394,-0.982927,...,0.010155,-0.169417,0.030952,-0.075127,0.047449,0.006925,0.040731,0.041316,0.138088,1.0
288,0.22,0.22,0.00,0.48,0.08,-0.027889,1.074085,-0.085856,0.182226,-0.370502,...,0.088382,-0.114413,0.029498,0.036496,0.119965,0.049349,-0.047043,-0.132503,-0.110066,1.0
337,0.14,0.22,0.06,0.50,0.08,-0.320405,-1.068282,0.303385,0.352710,-0.495233,...,-0.131822,0.045874,0.013079,-0.000264,0.029570,-0.009866,0.060963,-0.113867,-0.087169,1.0
343,0.34,0.06,0.16,0.33,0.11,0.076376,0.008851,0.351383,0.135071,-0.787341,...,-0.194412,0.141713,0.067840,0.066661,-0.005448,-0.081097,-0.013315,-0.067090,-0.051553,1.0
358,0.08,0.21,0.39,0.11,0.21,1.063438,0.815281,0.868849,0.370847,-0.183873,...,-0.041358,0.301959,-0.101482,0.281717,-0.157190,0.234508,-0.217071,-0.145044,0.353532,1.0
363,0.25,0.23,0.19,0.08,0.25,0.961320,0.715762,-0.499097,0.436138,0.054226,...,-0.058035,0.220709,-0.178002,-0.124160,-0.160490,0.130358,0.227710,-0.097250,0.196162,1.0
366,0.50,0.00,0.12,0.30,0.08,-0.640955,0.310383,0.645772,0.581231,1.341376,...,0.101852,-0.096307,0.130410,0.089639,-0.017909,0.018703,-0.141191,-0.026508,-0.178508,1.0
371,0.03,0.24,0.21,0.43,0.09,-0.498873,0.622192,-0.357388,-0.253052,-1.223165,...,0.114583,-0.126082,-0.030697,-0.124204,0.142590,-0.029199,-0.087279,-0.014966,-0.001732,1.0
378,0.21,0.19,0.20,0.17,0.23,1.124995,0.908850,-0.151682,0.621132,-0.393763,...,-0.178040,-0.088844,-0.424624,0.225392,-0.083131,-0.020375,-0.097594,0.133839,0.229881,1.0
382,0.47,0.04,0.06,0.33,0.10,0.579093,-0.598541,0.876620,-0.633920,-0.950575,...,0.035428,0.032998,0.004483,-0.042406,0.061491,-0.075528,0.127837,0.051777,-0.017344,1.0
387,0.26,0.31,0.00,0.32,0.11,-0.413456,-0.676966,-0.469155,-1.032925,-0.353657,...,-0.044997,-0.028069,-0.087728,-0.005616,-0.187666,-0.067435,-0.111124,0.016767,0.089056,1.0
390,0.10,0.09,0.50,0.22,0.09,-0.520585,0.927781,0.062481,0.399865,0.220935,...,0.114583,0.031785,-0.210798,-0.037158,-0.010946,0.026734,0.105921,-0.069115,0.010524,1.0
391,0.44,0.02,0.12,0.34,0.08,-0.825388,-0.911701,-0.010431,-0.800777,0.323474,...,-0.054565,-0.022445,0.030524,0.055433,-0.066080,-0.056122,-0.048410,-0.007198,0.068981,1.0
401,0.00,0.39,0.23,0.29,0.09,-0.986916,-0.436011,-1.092902,-0.031785,-0.011148,...,-0.009442,0.029201,0.099377,0.099751,-0.010920,-0.000887,-0.048043,0.037474,-0.039342,1.0
417,0.50,0.07,0.05,0.29,0.09,-0.927745,0.041303,-0.450185,-0.010022,0.488579,...,-0.023161,-0.072226,0.117175,0.045835,-0.063306,0.028698,-0.053080,-0.041815,-0.036442,1.0
446,0.24,0.41,0.02,0.12,0.21,0.320577,-0.318102,-1.736305,0.283791,0.211844,...,0.026008,-0.003970,0.011210,0.348388,0.047903,0.083419,-0.112979,-0.349017,0.179984,1.0
466,0.00,0.47,0.00,0.44,0.09,-1.207138,-0.591239,-0.289048,-1.526240,-0.130264,...,-0.023803,-0.189228,-0.060906,-0.142450,0.145044,0.112383,0.082313,-0.084132,0.155349,1.0
474,0.05,0.06,0.29,0.47,0.13,1.357982,1.363177,0.639372,1.640408,-0.156467,...,0.069118,0.169345,0.211916,0.143784,-0.044778,-0.040211,-0.155535,-0.009005,0.177231,1.0
487,0.33,0.27,0.00,0.33,0.07,-0.635468,-0.915758,-0.492697,-1.471830,-0.121307,...,-0.001118,0.060272,-0.065180,0.033023,-0.044232,0.039307,-0.156268,-0.149979,-0.079329,1.0
490,0.00,0.50,0.19,0.10,0.21,-0.054015,-0.404370,-1.425460,0.258400,-0.755657,...,-0.509630,-0.218549,-0.004280,0.359676,0.108929,0.026956,-0.404457,0.129730,0.094847,1.0
496,0.09,0.24,0.33,0.11,0.23,0.812557,1.299084,0.305671,0.526821,-1.173968,...,0.162213,0.268884,0.329443,0.135333,0.352231,0.187488,0.264330,-0.491871,-0.042761,1.0
506,0.37,0.00,0.19,0.33,0.11,0.368415,-0.049022,1.075240,0.791616,0.735100,...,-0.149159,-0.015105,0.106997,0.004319,0.085275,-0.156417,0.141905,0.089324,0.039048,1.0
512,0.44,0.12,0.07,0.27,0.10,-1.074599,-0.665608,-0.614978,-1.058316,-1.170358,...,0.036878,0.143790,0.096949,-0.078929,-0.109154,-0.082975,0.041517,0.005798,-0.067692,1.0
513,0.35,0.00,0.08,0.47,0.10,0.087829,0.065642,0.987701,-0.238543,0.877344,...,-0.073319,0.010999,-0.165912,0.083085,0.101341,0.020295,-0.094990,-0.135467,-0.167451,1.0
529,0.29,0.37,0.00,0.08,0.26,0.014938,0.726038,-0.468241,0.947590,0.655823,...,0.230546,-0.370551,0.008598,-0.154312,-0.397920,0.326500,0.088383,-0.500135,0.316082,1.0
538,0.50,0.13,0.07,0.20,0.10,-0.998727,-0.502537,-0.010202,-0.684703,0.527883,...,0.116185,-0.038131,0.029069,-0.013673,-0.040435,0.041710,0.018198,0.038201,-0.031205,1.0
554,0.12,0.03,0.28,0.46,0.11,0.003725,0.737667,0.705884,0.418002,0.230427,...,0.018829,-0.008638,-0.203904,-0.104185,-0.204467,-0.002961,-0.048143,-0.118948,0.046709,1.0
559,0.48,0.00,0.08,0.23,0.21,1.322312,1.015130,0.673428,0.878671,0.131097,...,-0.090398,-0.007853,-0.287580,-0.062608,0.185680,-0.246810,0.231386,0.024660,-0.409351,1.0
561,0.43,0.15,0.10,0.23,0.09,-1.072929,-0.690217,-0.733830,-1.377520,-0.461543,...,0.017631,0.049497,-0.043396,0.065334,-0.073864,0.003490,0.050067,0.040947,-0.060767,1.0
572,0.41,0.00,0.00,0.50,0.09,1.489328,0.184362,1.525051,0.178599,1.663966,...,-0.000817,-0.164759,0.146711,0.014536,0.041958,0.038790,0.015593,0.023933,0.089392,1.0
575,0.03,0.29,0.37,0.18,0.13,-1.028551,0.592444,-0.314647,-0.140605,-0.345368,...,0.165509,-0.079747,0.070030,0.141904,0.112387,-0.033081,0.103529,-0.159849,-0.051377,1.0
576,0.35,0.31,0.00,0.22,0.12,-1.683013,-1.038264,-0.837598,-1.094589,-0.410341,...,-0.011848,-0.261843,0.033985,0.209164,0.220396,0.088723,-0.059486,-0.193682,-0.054203,1.0
578,0.12,0.12,0.34,0.32,0.10,0.004440,0.279283,0.388868,0.200363,-0.359673,...,0.026225,0.082460,0.117367,0.107902,0.014469,0.095631,-0.027996,-0.121735,-0.027047,1.0
592,0.22,0.28,0.08,0.34,0.08,-0.135972,-0.076606,-1.214040,-0.648429,-0.748171,...,0.052484,-0.148175,0.130410,0.026062,0.144097,0.103933,0.140724,-0.033770,-0.053045,1.0
595,0.50,0.09,0.00,0.33,0.08,-1.355901,-0.914947,0.369897,0.120562,-0.372373,...,-0.105245,0.036556,0.085256,-0.045451,-0.038569,0.124058,0.140724,-0.041381,0.024878,1.0
600,0.10,0.50,0.07,0.20,0.13,-0.855570,-1.022579,-2.167145,-1.801916,-0.918356,...,-0.024614,-0.058900,-0.146480,-0.049292,0.191649,-0.155354,0.074031,-0.209345,0.090608,1.0
603,0.12,0.06,0.47,0.14,0.21,0.736684,2.249655,0.380639,0.951217,-1.081322,...,0.175873,-0.203189,-0.052544,-0.162513,-0.407906,0.153780,0.369400,-0.358121,-0.266146,1.0
610,0.26,0.21,0.11,0.30,0.12,-1.014354,-0.457916,-0.333618,0.116935,-0.335743,...,0.152777,0.029396,-0.258102,-0.241194,-0.079063,-0.054932,0.040709,-0.097627,-0.127343,1.0
614,0.45,0.12,0.07,0.15,0.21,0.181954,1.175226,0.270244,0.461530,-0.209274,...,0.267360,0.072657,0.125248,-0.123090,0.289265,-0.289221,-0.152229,0.188606,0.250786,1.0
616,0.00,0.50,0.18,0.24,0.08,-1.441676,-0.769183,-1.932183,-0.822541,-0.174648,...,0.101852,-0.092818,0.096972,-0.140844,-0.006673,0.077509,0.050676,0.115876,-0.060668,1.0
647,0.50,0.00,0.11,0.29,0.10,-0.366453,-0.969574,0.011511,-0.492455,0.549006,...,-0.168368,0.006611,-0.012835,-0.069501,0.155698,0.025780,0.003029,-0.028214,-0.101823,1.0
648,0.07,0.12,0.26,0.47,0.08,1.050554,0.708189,0.696284,0.860535,0.055830,...,0.072764,-0.075307,-0.134526,-0.042645,0.025299,-0.094988,-0.007919,0.134962,-0.162679,1.0
649,0.00,0.50,0.08,0.34,0.08,-1.272871,-0.634508,-1.786131,-1.323110,-1.530381,...,0.022312,0.012664,0.032577,0.048197,0.002912,-0.065054,-0.016497,0.069888,0.133265,1.0
661,0.19,0.09,0.42,0.20,0.10,-0.447933,0.640040,0.177448,-0.633920,-0.426784,...,-0.151270,-0.047681,-0.151802,0.111094,-0.022137,0.088330,-0.037001,-0.008888,0.055422,1.0
668,0.10,0.39,0.18,0.21,0.12,-1.370813,-0.331894,-1.383633,-0.887832,0.103022,...,-0.111896,0.172548,-0.072998,0.207756,-0.013581,0.108044,-0.052530,0.057052,0.114033,1.0
680,0.26,0.05,0.35,0.11,0.23,0.564181,0.559181,0.120307,1.081801,-1.202310,...,-0.398623,0.114112,0.315182,-0.035120,0.121467,-0.262466,-0.185113,-0.358989,-0.009767,1.0
681,0.50,0.00,0.00,0.42,0.08,-0.288553,-0.917921,0.883248,0.233009,2.176392,...,0.031538,0.115032,-0.163602,-0.040550,-0.151122,-0.009642,-0.021553,-0.054055,0.017809,1.0
682,0.09,0.25,0.29,0.23,0.14,-0.056282,-0.445205,-0.626863,-0.006394,-0.179461,...,-0.035496,0.201306,0.035309,-0.110500,0.188126,0.198059,-0.095542,-0.157403,0.051249,1.0
689,0.00,0.39,0.31,0.20,0.10,-1.407318,-0.203979,-1.581339,0.392611,-0.698439,...,0.029364,-0.011606,0.106998,0.173812,0.036770,0.097032,0.067050,-0.212178,0.042220,1.0
704,0.00,0.12,0.36,0.42,0.10,0.511332,0.465071,1.197521,1.306695,0.116792,...,0.079659,-0.048978,0.082625,-0.009157,0.110481,-0.098661,-0.096742,-0.033463,-0.094442,1.0
705,0.50,0.20,0.00,0.22,0.08,-1.055631,-2.394212,-0.841483,-1.703979,0.013852,...,-0.026390,-0.047927,0.016842,-0.040004,0.092555,-0.003996,0.064115,-0.060129,-0.100419,1.0
706,0.29,0.01,0.13,0.47,0.10,0.555830,0.470479,0.631372,0.323692,0.132834,...,0.108219,0.141471,-0.067032,0.076795,-0.134729,0.021539,-0.041900,0.039318,0.034147,1.0
708,0.09,0.08,0.50,0.23,0.10,-1.059210,0.504283,0.401896,-0.187760,-0.691487,...,0.127314,0.105176,0.146015,0.095923,-0.052973,0.196975,-0.064845,0.126800,0.098527,1.0
720,0.42,0.17,0.00,0.32,0.09,0.169666,0.001279,-0.075571,-1.221545,0.887905,...,0.026470,0.039709,-0.017227,0.061331,-0.156301,0.050198,-0.063648,-0.057065,-0.065632,1.0
727,0.00,0.50,0.11,0.30,0.09,-0.753333,-0.879249,-1.930583,-1.167136,-0.072778,...,0.053052,0.049198,-0.135756,-0.081141,-0.017487,0.093746,-0.006375,0.074778,0.068279,1.0
752,0.00,0.19,0.50,0.22,0.09,-0.357745,1.316122,0.484407,0.534076,0.046205,...,-0.026650,-0.127175,0.023372,-0.138386,0.040860,-0.033246,0.032085,0.101522,0.081097,1.0
759,0.03,0.32,0.07,0.50,0.08,-0.391386,-0.017922,0.435723,-0.307462,-1.463135,...,0.018431,-0.054816,-0.144788,-0.014944,0.071496,0.018118,0.036596,-0.130915,0.126390,1.0
766,0.50,0.00,0.20,0.21,0.09,-0.676029,-0.327026,0.682342,-1.123608,0.779351,...,0.098360,0.079008,-0.100351,0.087399,0.165297,0.107897,0.157883,0.151832,-0.044425,1.0
774,0.18,0.00,0.50,0.22,0.10,0.636833,0.125407,-0.042658,0.363592,1.457685,...,-0.047161,0.135371,0.013783,0.031704,0.183663,-0.067386,-0.099592,0.009790,-0.102204,1.0
781,0.30,0.12,0.25,0.19,0.14,-0.548023,-0.586101,-0.695660,0.196736,0.291522,...,-0.345546,-0.108719,-0.104021,-0.179109,-0.049499,-0.152630,-0.225361,0.102684,-0.169136,1.0
798,0.00,0.10,0.50,0.31,0.09,0.684671,0.578652,-0.090199,1.114447,0.689646,...,0.019814,-0.132019,0.043768,-0.119574,0.101990,0.138786,-0.167863,-0.116669,-0.042773,1.0
803,0.10,0.09,0.50,0.19,0.12,-1.035709,-0.348390,0.329441,-0.165996,0.094600,...,-0.073771,-0.054468,0.074521,-0.253342,-0.012510,0.118896,-0.242918,0.021609,-0.084349,1.0
805,0.50,0.00,0.08,0.29,0.13,-0.263620,0.437757,-0.201737,0.726324,1.432952,...,0.165509,0.031056,0.134233,-0.212661,-0.054488,-0.374454,0.104209,0.143281,-0.085882,1.0
837,0.08,0.50,0.00,0.30,0.12,-1.180654,-0.978228,-0.802856,-1.138117,-0.634135,...,-0.122854,-0.125349,0.097226,-0.114066,0.033410,-0.088601,-0.195740,0.106791,-0.122645,1.0
838,0.19,0.00,0.50,0.19,0.12,-0.247037,0.991062,0.571260,-0.822541,1.830274,...,0.047564,-0.105277,0.133913,0.023949,-0.016392,-0.097947,-0.151260,0.054624,0.073866,1.0
839,0.19,0.50,0.00,0.18,0.13,-1.266667,-1.360619,-2.059492,-1.645942,-0.125451,...,-0.039452,-0.146021,-0.070743,0.165564,0.000950,0.178905,0.044668,0.219313,0.224394,1.0
859,0.30,0.00,0.38,0.10,0.22,2.321781,1.304764,1.372371,0.124189,2.087891,...,-0.115838,-0.195133,0.071008,0.307469,-0.018352,0.118523,0.234887,0.002256,0.085032,1.0
866,0.05,0.24,0.30,0.30,0.11,-1.319038,0.772282,1.045984,-0.641175,-1.069424,...,-0.046567,-0.155071,-0.162866,-0.027092,0.144920,-0.047351,0.136238,-0.120709,-0.017668,1.0
868,0.23,0.21,0.00,0.48,0.08,-0.068331,-0.942260,0.316413,-0.858814,-0.096574,...,-0.147555,-0.047839,-0.041824,-0.141848,0.028241,0.012785,-0.043047,-0.099900,-0.005254,1.0
879,0.07,0.50,0.07,0.14,0.22,-0.331380,-0.235890,-1.842358,0.664659,-0.874506,...,-0.020936,-0.051766,0.335344,0.027398,0.171163,0.002284,0.130173,0.226115,0.379743,1.0
886,0.06,0.50,0.06,0.31,0.07,-1.575169,-1.271106,-2.404164,-1.667705,-0.227589,...,-0.001118,-0.189877,-0.066078,-0.013267,0.065012,-0.041813,0.042548,0.118091,-0.110060,1.0
887,0.25,0.09,0.08,0.50,0.08,0.974562,0.034542,0.444865,-0.463436,-0.358470,...,-0.062498,-0.019045,-0.054566,0.022395,0.022934,-0.047542,-0.145703,-0.036751,0.072335,1.0
892,0.00,0.19,0.50,0.22,0.09,-0.603616,-0.127177,0.760967,0.650150,-0.643359,...,-0.084093,-0.225173,0.094277,0.071498,0.056542,0.009677,0.013977,0.151832,-0.003354,1.0
897,0.19,0.50,0.00,0.20,0.11,-1.474959,-1.360078,-1.994809,-1.051062,-1.285597,...,0.140046,0.031379,-0.043515,0.107496,0.202030,-0.050757,-0.164833,0.185572,0.143485,1.0
899,0.48,0.00,0.00,0.44,0.08,0.787862,-0.042531,0.001226,-1.703979,1.252072,...,-0.056943,-0.097676,0.054555,-0.014682,0.102900,-0.012274,-0.065384,-0.006329,0.023908,1.0
902,0.14,0.17,0.32,0.14,0.23,0.544139,0.782829,0.419952,0.265655,-0.748037,...,-0.230492,0.270217,0.006868,-0.143693,0.172054,0.382036,-0.105273,0.264870,0.226135,1.0
908,0.32,0.12,0.14,0.32,0.10,-0.677937,-0.348931,-0.029630,0.073407,-1.288138,...,0.041825,0.132308,0.125919,0.001757,-0.194308,-0.061865,-0.015086,-0.036244,0.171328,1.0

In [44]:
train_df['Total_Fraction'].sum()

np.float64(2000.0)

Every row has a right proportion values. We just have to check why the sum is equal to the no of rows above but while checking the condition we are not getting the correctly. 
```
are_all_ones_cola = (train_df['Total_Fraction'] == 1).all()
print(f"Are all values in 'Total_Fraction' equal to 1? {are_all_ones_cola}")
```
Shoudl return true. Maybe there is something wrong in the way we are trying to calculate the values.
`NOTE:` we are rmeoving the Total fraction column for the time being.

In [47]:
train_df.drop('Total_Fraction',axis=1,inplace=True)

In [48]:
train_df.shape

(2000, 65)

In [49]:
def create_features(df):    
    # Volume fractions
    fractions = ['Component1_fraction', 'Component2_fraction', 
                 'Component3_fraction', 'Component4_fraction', 
                 'Component5_fraction']
    # Fraction statistics
    df['max_fraction'] = df[fractions].max(axis=1)
    df['min_fraction'] = df[fractions].min(axis=1)
    df['fraction_range'] = df['max_fraction'] - df['min_fraction']
    
    # Property aggregations
    for prop_idx in range(1, 11):
        prop_cols = [f'Fraction{i}_Property{prop_idx}' for i in range(1,6)]
        df[f'mean_prop_{prop_idx}'] = df[prop_cols].mean(axis=1)
        df[f'std_prop_{prop_idx}'] = df[prop_cols].std(axis=1)
    
    return df

In [50]:
create_features(train_df)

,Component1_fraction,Component2_fraction,Component3_fraction,Component4_fraction,Component5_fraction,BlendProperty1,BlendProperty2,BlendProperty3,BlendProperty4,BlendProperty5,...,mean_prop_6,std_prop_6,mean_prop_7,std_prop_7,mean_prop_8,std_prop_8,mean_prop_9,std_prop_9,mean_prop_10,std_prop_10
0,0.21,0.00,0.42,0.25,0.12,0.489143,0.607589,0.321670,-1.236055,1.601132,...,0.106933,0.347232,-0.120161,0.248658,-0.066186,0.186459,0.000750,0.141703,-0.094515,0.229165
1,0.02,0.33,0.19,0.46,0.00,-1.257481,-1.475283,-0.437385,-1.402911,0.147941,...,-0.019265,0.189665,0.090867,0.121365,-0.041473,0.236670,-0.026148,0.081243,-0.123097,0.245462
2,0.08,0.08,0.18,0.50,0.16,1.784349,0.450467,0.622687,1.375614,-0.428790,...,-0.004289,0.224121,-0.076954,0.173544,0.007938,0.324994,-0.089944,0.175683,-0.012079,0.047915
3,0.25,0.42,0.00,0.07,0.26,-0.066422,0.483730,-1.865442,-0.046295,-0.163820,...,-0.046703,0.144124,-0.149895,0.291326,0.165193,0.496176,0.026022,0.280656,-0.079800,0.225990
4,0.26,0.16,0.08,0.50,0.00,-0.118913,-1.172398,0.301785,-1.787407,-0.493361,...,0.062587,0.084277,0.022690,0.180814,0.089542,0.355805,0.199487,0.412474,0.201004,0.247927
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,0.50,0.12,0.00,0.26,0.12,-0.028366,-0.327297,-0.316933,-1.294092,-0.530259,...,-0.012711,0.187847,0.047059,0.188609,0.103237,0.517661,0.193360,0.221850,-0.001237,0.130532
1996,0.19,0.31,0.00,0.37,0.13,-0.449245,0.156778,-0.367445,-0.938615,-0.577451,...,-0.009367,0.250814,-0.084016,0.228746,0.092658,0.198032,0.051204,0.323422,0.064496,0.086924
1997,0.38,0.06,0.14,0.31,0.11,0.029135,0.164890,-0.092942,-1.134490,-0.437479,...,-0.134388,0.381766,-0.085456,0.100597,0.055603,0.191259,0.005161,0.220482,-0.094395,0.099326
1998,0.50,0.16,0.00,0.18,0.16,-0.232960,-0.464947,0.112536,-0.793522,-0.811272,...,-0.160370,0.208162,0.209297,0.173494,0.159026,0.418624,0.106862,0.304090,0.083929,0.133171
1999,0.00,0.34,0.21,0.45,0.00,-1.797180,-1.312212,-0.511896,-1.450066,-0.365154,...,-0.003494,0.135306,-0.026953,0.164207,0.184117,0.259159,-0.027173,0.168598,0.072221,0.095965

In [51]:
train_df.shape

(2000, 88)

In [52]:
train_df.head().T

                             0         1         2         3         4
Component1_fraction   0.210000  0.020000  0.080000  0.250000  0.260000
Component2_fraction   0.000000  0.330000  0.080000  0.420000  0.160000
Component3_fraction   0.420000  0.190000  0.180000  0.000000  0.080000
Component4_fraction   0.250000  0.460000  0.500000  0.070000  0.500000
Component5_fraction   0.120000  0.000000  0.160000  0.260000  0.000000
BlendProperty1        0.489143 -1.257481  1.784349 -0.066422 -0.118913
BlendProperty2        0.607589 -1.475283  0.450467  0.483730 -1.172398
BlendProperty3        0.321670 -0.437385  0.622687 -1.865442  0.301785
BlendProperty4       -1.236055 -1.402911  1.375614 -0.046295 -1.787407
BlendProperty5        1.601132  0.147941 -0.428790 -0.163820 -0.493361
BlendProperty6        1.384662 -1.143244  1.161616 -0.209693 -0.528049
BlendProperty7        0.305850 -0.439171  0.601289 -1.840566  0.286344
BlendProperty8        0.193460 -1.379041  0.872950  0.300293 -0.265192
BlendProperty9        0.580374 -1.280989  0.660000 -0.351336  0.430513
BlendProperty10      -0.762738 -0.503625  2.024576 -1.551914  0.735073
Fraction1_Property1  -0.004574 -0.004487  0.036621 -0.144433  0.031308
Fraction1_Property2  -0.258258 -0.021501  0.019232 -0.146954  0.033180
Fraction1_Property3  -0.082598 -0.013822 -0.021650  0.228235  0.349018
Fraction1_Property4  -0.370248 -0.037394 -0.245031  0.183744 -0.150816
Fraction1_Property5   0.010874 -0.007507  0.014868 -0.059567  0.166018
Fraction1_Property6  -0.311500 -0.004443 -0.121557 -0.286452  0.038620
Fraction1_Property7  -0.106970 -0.024093  0.001650 -0.134765 -0.154158
Fraction1_Property8   0.061701  0.018967 -0.053691  0.188626 -0.206162
Fraction1_Property9   0.100877 -0.039177 -0.063918 -0.133534 -0.101231
Fraction1_Property10 -0.261442 -0.023209  0.000546  0.013243  0.547280
Fraction2_Property1   0.000000  0.378852  0.019407 -0.390947  0.106603
Fraction2_Property2  -0.000000  0.294636  0.176800  0.824284 -0.028389
Fraction2_Property3   0.000000 -0.084354  0.114724 -0.216245 -0.001087
Fraction2_Property4   0.000000  0.295757 -0.022286 -0.097038 -0.172783
Fraction2_Property5   0.000000  0.357049 -0.001625  0.204167 -0.022996
Fraction2_Property6  -0.000000  0.113556 -0.008235  0.057073  0.045127
Fraction2_Property7  -0.000000  0.262611  0.163667 -0.654816  0.328173
Fraction2_Property8  -0.000000  0.268165  0.031825  0.987736  0.009660
Fraction2_Property9   0.000000 -0.006469 -0.035522  0.485315  0.287878
Fraction2_Property10 -0.000000 -0.004711  0.053499 -0.430410  0.137375
Fraction3_Property1   0.008415 -0.210490 -0.166049  0.000000 -0.050155
Fraction3_Property2   0.056279  0.259060 -0.477434 -0.000000 -0.121403
Fraction3_Property3   0.275564  0.241447  0.089893  0.000000 -0.029653
Fraction3_Property4  -0.650208 -0.292828  0.064135  0.000000 -0.106429
Fraction3_Property5  -0.180965 -0.003283 -0.130405  0.000000 -0.019131
Fraction3_Property6   0.631446  0.133639  0.110473 -0.000000  0.019188
Fraction3_Property7  -0.553424  0.047211 -0.304124 -0.000000 -0.035434
Fraction3_Property8  -0.385556 -0.109198  0.386804 -0.000000 -0.062847
Fraction3_Property9  -0.189401 -0.153505  0.026713 -0.000000 -0.072990
Fraction3_Property10 -0.132058 -0.025834  0.002781  0.000000 -0.037529
Fraction4_Property1   0.035079  0.068785  0.454106  0.031326  1.362679
Fraction4_Property2   0.204459 -0.802095 -0.296925  0.018826  0.057239
Fraction4_Property3   0.018615 -0.153547 -0.470837  0.022345  0.288255
Fraction4_Property4  -0.413572 -0.112579  0.240160  0.069470 -0.761230
Fraction4_Property5   0.435902 -0.880302 -1.067902  0.032432  0.660765
Fraction4_Property6   0.005761 -0.339076 -0.295989  0.063779  0.210000
Fraction4_Property7   0.033039  0.168608 -0.139566  0.065198 -0.025131
Fraction4_Property8  -0.068676 -0.385297 -0.491557 -0.019290  0.707058
Fraction4_Property9   0.168643  0.068409 -0.396804  0.031511  0.883779
Fraction4_Property10  0.248398 -0.561731 -0.049330  0.168039  0.357894
Fraction5_Property1   0.123843 -0.000000  0.155521  0.118486  0.000000
Fraction5_Property2   0.025934  0.000000 -0.108521  0.053903  0.000000
Fraction5_Property3  -0.369953 -0.000000  0.230064 -0.347874  0.000000
Fraction5_Property4  -0.169206 -0.000000 -0.007537 -0.252382  0.000000
Fraction5_Property5   0.035606 -0.000000 -0.488454  0.277352  0.000000
Fraction5_Property6   0.208956  0.000000  0.293861 -0.067915 -0.000000
Fraction5_Property7   0.026548  0.000000 -0.106395 -0.025092  0.000000
Fraction5_Property8   0.061599  0.000000  0.166308 -0.331107  0.000000
Fraction5_Property9  -0.076367  0.000000  0.019813 -0.253182 -0.000000
Fraction5_Property10 -0.327471  0.000000 -0.067890 -0.149872 -0.000000
max_fraction          0.420000  0.460000  0.500000  0.420000  0.500000
min_fraction          0.000000  0.000000  0.080000  0.000000  0.000000
fraction_range        0.420000  0.460000  0.420000  0.420000  0.500000
mean_prop_1           0.032553  0.046532  0.099921 -0.077114  0.290087
std_prop_1            0.053294  0.213167  0.229002  0.199367  0.602287
mean_prop_2           0.005683 -0.053980 -0.137370  0.150012 -0.011875
std_prop_2            0.167466  0.442485  0.257469  0.384637  0.069312
mean_prop_3          -0.031674 -0.002055 -0.011561 -0.062708  0.121307
std_prop_3            0.231815  0.149298  0.271873  0.224002  0.181802
mean_prop_4          -0.320647 -0.029409  0.005888 -0.019241 -0.238252
std_prop_4            0.247717  0.213874  0.174793  0.165718  0.299825
mean_prop_5           0.060283 -0.106809 -0.334704  0.090877  0.156931
std_prop_5            0.226922  0.459740  0.457192  0.143104  0.292374
mean_prop_6           0.106933 -0.019265 -0.004289 -0.046703  0.062587
std_prop_6            0.347232  0.189665  0.224121  0.144124  0.084277
mean_prop_7          -0.120161  0.090867 -0.076954 -0.149895  0.022690
std_prop_7            0.248658  0.121365  0.173544  0.291326  0.180814
mean_prop_8          -0.066186 -0.041473  0.007938  0.165193  0.089542
std_prop_8            0.186459  0.236670  0.324994  0.496176  0.355805
mean_prop_9           0.000750 -0.026148 -0.089944  0.026022  0.199487
std_prop_9            0.141703  0.081243  0.175683  0.280656  0.412474
mean_prop_10         -0.094515 -0.123097 -0.012079 -0.079800  0.201004
std_prop_10           0.229165  0.245462  0.047915  0.225990  0.247927

In [54]:
# as there is no Total_fraction, no need to check
# train_df = train_df[abs(train_df['Total_Fraction'] - 1) < 1e-6]  # Using 1e-6 tolerance

In [55]:
# print(f"Rows remaining: {len(train_df)}")

Rows remaining: 2000

In [56]:
train_df.shape

(2000, 88)

### Saving Train file

In [57]:
!pwd

/home/pkn/workspace/side_projects/he_shellai_2025/notebooks

In [58]:
processed_folder = "../data/processed/"

In [59]:
train_df.to_csv(processed_folder+"processed_train.csv",index=False)

# Test File preparation

`NOTE`: Additinal `ID` columns is present in the dataframe

In [60]:
id_column = test_df[['ID']]
test_df = test_df.drop('ID',axis =1)

In [61]:
test_df.head(3).T

                              0         1         2
Component1_fraction    0.180000  0.000000  0.160000
Component2_fraction    0.050000  0.500000  0.000000
Component3_fraction    0.320000  0.000000  0.170000
Component4_fraction    0.370000  0.370000  0.500000
Component5_fraction    0.080000  0.130000  0.170000
Component1_Property1  -0.177804  2.501354  1.547324
Component2_Property1  -0.741219  0.177344  0.891479
Component3_Property1   0.769821 -0.498739  0.030627
Component4_Property1  -0.877069 -0.196742 -0.368678
Component5_Property1   0.602809 -1.943463 -0.294728
Component1_Property2   0.916160 -1.573087 -0.368465
Component2_Property2  -0.961287  1.150655  1.885650
Component3_Property2   2.203840 -2.224119  1.468301
Component4_Property2  -1.543814 -1.364494 -0.573632
Component5_Property2  -2.190197  0.321700 -0.883240
Component1_Property3   0.729395  1.133394 -0.300552
Component2_Property3   1.879598  1.015871 -1.575312
Component3_Property3  -0.929492  0.580352 -0.742060
Component4_Property3  -0.045910  0.222919  1.241059
Component5_Property3  -1.204109  0.175686  1.437899
Component1_Property4  -0.574983  0.552191 -1.321355
Component2_Property4  -0.557002  0.611019 -0.353278
Component3_Property4  -0.089556  0.418521  0.746869
Component4_Property4   2.858307  0.470180 -0.290370
Component5_Property4   0.265037  1.605533 -1.913537
Component1_Property5  -0.263618  0.708142  1.719005
Component2_Property5   1.470090 -0.591893  0.608247
Component3_Property5   0.068222  0.649334  0.314285
Component4_Property5   1.126505 -1.704094  0.824464
Component5_Property5  -0.591598  0.152504  1.536746
Component1_Property6   0.265062 -0.273166 -1.444898
Component2_Property6   0.710262  0.346800 -1.830772
Component3_Property6   0.230021  0.222380  1.652564
Component4_Property6   0.892238  0.821263  0.623479
Component5_Property6  -0.083417 -0.072760  0.629306
Component1_Property7   0.464418 -0.724970 -0.125655
Component2_Property7  -0.368218  0.677438  0.308951
Component3_Property7  -0.695951  1.354104 -1.523949
Component4_Property7  -0.873687  1.486286 -0.529214
Component5_Property7  -1.631855  1.236025  0.144451
Component1_Property8   1.688636 -1.024885  0.928781
Component2_Property8  -0.875927  0.055721  0.143440
Component3_Property8  -0.751733 -0.422128  1.025281
Component4_Property8   0.424131 -0.206051  0.505345
Component5_Property8  -0.670066  0.589603 -0.208478
Component1_Property9  -0.265376 -0.787677 -0.710026
Component2_Property9   0.123432 -0.757905 -1.422693
Component3_Property9   0.028533 -0.280561  0.874071
Component4_Property9  -0.173365 -1.965970 -1.016144
Component5_Property9   1.297923  0.543475  0.093525
Component1_Property10  0.323299 -0.906851  1.048525
Component2_Property10 -0.315146  0.962341 -1.321851
Component3_Property10  0.625518 -0.183757  0.356640
Component4_Property10 -0.514342  0.310871 -0.869543
Component5_Property10 -0.777057 -1.329042 -0.177255

In [62]:
test_df.shape

(500, 55)

## 1. Multiply each ComponentX_fraction with its respective properties

In [63]:
for comp_num in range(1, 6):  # For components 1 through 5
    for prop_num in range(1, 11):  # For properties 1 through 10
        # Original column name
        orig_col = f'Component{comp_num}_Property{prop_num}'
        # New column name
        new_col = f'Fraction{comp_num}_Property{prop_num}'
        # Multiply fraction with property and create new column
        test_df[new_col] = test_df[f'Component{comp_num}_fraction'] * test_df[orig_col]

In [64]:
cols_to_drop = [f'Component{comp_num}_Property{prop_num}' 
                for comp_num in range(1, 6) 
                for prop_num in range(1, 11)]

In [65]:
test_df = test_df.drop(columns=cols_to_drop)

In [66]:
test_df.shape

(500, 55)

## 2. Calculate sum of all 5 component fractions

In [67]:

test_df['Total_Fraction'] = (test_df['Component1_fraction'] + 
                             test_df['Component2_fraction'] + 
                             test_df['Component3_fraction'] + 
                             test_df['Component4_fraction'] + 
                             test_df['Component5_fraction'])

In [68]:
are_all_ones_cola = (test_df['Total_Fraction'] == 1).all()
print(f"Are all values in 'Total_Fraction' equal to 1? {are_all_ones_cola}")

Are all values in 'Total_Fraction' equal to 1? False

In [69]:
(test_df['Total_Fraction'] == 1).value_counts()

Total_Fraction
True     459
False     41
Name: count, dtype: int64

In [70]:
test_df[test_df['Total_Fraction'] != 1]

,Component1_fraction,Component2_fraction,Component3_fraction,Component4_fraction,Component5_fraction,Fraction1_Property1,Fraction1_Property2,Fraction1_Property3,Fraction1_Property4,Fraction1_Property5,...,Fraction5_Property2,Fraction5_Property3,Fraction5_Property4,Fraction5_Property5,Fraction5_Property6,Fraction5_Property7,Fraction5_Property8,Fraction5_Property9,Fraction5_Property10,Total_Fraction
13,0.40,0.00,0.20,0.33,0.07,0.610388,0.327643,-0.192641,-0.410747,0.738994,...,0.030343,0.023427,0.114108,0.005251,-0.061993,0.063682,-0.024449,0.014847,0.055823,1.0
25,0.05,0.16,0.49,0.20,0.10,-0.024017,0.019463,-0.045228,0.066959,-0.021979,...,-0.154671,0.062945,0.128591,0.035429,-0.025795,0.223814,-0.027342,0.111529,-0.071087,1.0
63,0.49,0.00,0.12,0.30,0.09,0.165998,-0.186492,0.173130,-0.281741,-0.433420,...,0.042843,0.076226,-0.003951,-0.137809,0.096711,-0.213692,-0.063625,0.038866,0.022748,1.0
89,0.50,0.00,0.00,0.41,0.09,0.050148,-0.271776,-0.117856,-1.531445,0.464396,...,-0.069882,0.129411,0.055121,-0.139086,0.014378,0.097991,-0.179105,-0.056256,-0.088148,1.0
96,0.24,0.04,0.36,0.27,0.09,0.546468,-0.152879,0.109577,-0.251323,0.151185,...,-0.129744,0.013502,0.146711,-0.079447,0.043565,0.151456,0.030665,0.116244,0.038497,1.0
99,0.18,0.14,0.26,0.33,0.09,0.326443,-0.018991,-0.080853,0.120415,0.172945,...,-0.010941,-0.070313,0.146711,0.095601,0.137069,-0.003607,-0.043767,-0.183479,-0.161247,1.0
104,0.30,0.04,0.10,0.47,0.09,0.355735,0.197436,0.166897,-0.099381,-0.166937,...,0.014314,-0.047186,-0.037335,-0.043077,-0.023907,-0.160436,-0.073102,-0.041872,0.048570,1.0
127,0.21,0.36,0.06,0.13,0.24,0.086047,-0.009350,-0.045415,0.202326,-0.221305,...,0.047702,0.345096,-0.056202,0.213712,-0.186212,-0.173135,0.042084,-0.031698,0.185820,1.0
138,0.50,0.00,0.10,0.32,0.08,0.172657,-0.494733,-0.441055,0.408107,0.504680,...,0.023529,-0.080651,0.130410,0.000871,-0.076486,0.120616,-0.002284,-0.069378,0.052293,1.0
143,0.50,0.07,0.06,0.31,0.06,0.689603,0.663987,0.857725,1.131631,0.055109,...,0.028434,0.020792,-0.095378,0.041288,0.038110,0.020536,0.056345,-0.082654,0.041549,1.0
160,0.18,0.50,0.00,0.10,0.22,0.202465,0.081693,-0.050598,-0.087046,-0.074136,...,0.280092,0.014787,0.042081,0.147398,-0.146722,0.271523,0.250421,-0.011132,-0.113855,1.0
164,0.50,0.12,0.08,0.21,0.09,0.187407,-0.047016,-0.518613,0.423339,-0.824696,...,-0.157823,-0.064450,0.046847,0.034121,0.003647,-0.070202,-0.053731,0.043654,0.140817,1.0
189,0.00,0.50,0.11,0.30,0.09,-0.000000,-0.000000,0.000000,-0.000000,0.000000,...,-0.096720,-0.082609,0.146711,-0.045484,-0.110283,0.201432,0.016825,-0.305149,0.030015,1.0
195,0.05,0.03,0.49,0.31,0.12,0.149057,0.018266,-0.037272,-0.028241,0.078409,...,-0.094460,-0.306889,0.111593,-0.097891,0.046969,-0.268747,0.032267,-0.018296,0.136528,1.0
213,0.50,0.00,0.09,0.31,0.10,0.130380,0.176269,0.296616,0.522348,-0.247505,...,-0.080667,0.119252,0.029283,0.050464,-0.042375,-0.030736,0.052579,-0.160551,-0.024517,1.0
224,0.50,0.08,0.08,0.23,0.11,-0.830500,0.686283,-0.090674,-0.411887,0.428946,...,-0.189155,0.128749,0.117933,0.050077,0.055960,-0.118757,0.193495,-0.044405,0.162657,1.0
227,0.16,0.17,0.27,0.29,0.11,0.188086,-0.108267,-0.373362,0.214269,-0.169129,...,-0.073876,0.121401,-0.095018,0.093524,-0.009176,-0.068293,0.036002,0.082441,-0.012904,1.0
230,0.09,0.50,0.09,0.11,0.21,-0.040465,0.001393,0.052314,0.030505,-0.147266,...,0.265363,0.288338,0.342325,0.168318,0.304224,0.247612,-0.388421,-0.263418,-0.247300,1.0
236,0.25,0.00,0.34,0.32,0.09,-0.088240,0.176826,-0.130251,-0.010465,-0.088195,...,0.101100,-0.105662,0.011443,0.099187,-0.005754,0.005640,-0.102131,-0.016133,-0.052035,1.0
240,0.00,0.36,0.11,0.41,0.12,-0.000000,-0.000000,-0.000000,-0.000000,0.000000,...,0.152777,-0.068446,0.063232,0.074718,0.145848,0.036435,-0.000706,0.002515,-0.221440,1.0
243,0.29,0.16,0.09,0.24,0.22,0.578772,-0.238071,-0.345490,-0.057785,0.297325,...,0.280092,0.078182,0.018799,-0.221427,0.189622,-0.227700,-0.224857,0.371144,-0.213337,1.0
253,0.50,0.00,0.00,0.41,0.09,-0.006879,-0.084066,-0.646296,1.121476,0.420137,...,-0.026757,-0.064252,-0.085535,0.013603,-0.002894,0.032493,0.007191,0.106513,-0.086245,1.0
258,0.50,0.06,0.05,0.16,0.23,-0.415326,-0.175216,-0.770239,0.012073,-0.255025,...,0.118840,0.131316,0.115295,-0.298080,-0.017773,-0.423599,0.080671,-0.441295,0.397004,1.0
263,0.09,0.25,0.36,0.20,0.10,0.008460,0.212235,-0.231249,-0.043523,0.042811,...,-0.004547,0.049365,0.163012,-0.060483,-0.092766,0.061236,0.070502,-0.013059,0.096067,1.0
274,0.18,0.00,0.49,0.22,0.11,-0.065466,-0.006302,-0.087945,-0.066940,-0.018253,...,0.104209,-0.089278,0.179313,-0.066426,-0.015142,-0.236350,-0.177903,-0.118656,0.018618,1.0
330,0.21,0.24,0.19,0.28,0.08,0.076508,-0.435076,0.492951,-0.168727,0.000767,...,-0.013853,-0.058261,0.023854,0.012986,-0.007879,0.041549,0.030047,0.088154,0.063188,1.0
341,0.22,0.48,0.00,0.21,0.09,0.169330,0.030960,0.158931,0.358290,-0.050292,...,0.114583,-0.091279,0.022603,0.000722,0.037102,-0.097362,-0.005786,0.003566,0.004973,1.0
371,0.27,0.19,0.13,0.33,0.08,-0.242306,-0.224220,-0.311698,0.183364,0.214692,...,0.013998,0.063009,-0.048751,0.021620,0.030192,-0.088875,0.096934,0.011563,-0.064549,1.0
375,0.00,0.00,0.47,0.44,0.09,0.000000,-0.000000,0.000000,0.000000,-0.000000,...,-0.065174,-0.090583,0.146711,-0.157799,0.055229,-0.096572,0.114637,-0.214533,-0.011244,1.0
376,0.11,0.24,0.27,0.29,0.09,0.000143,-0.249176,0.014287,0.116034,-0.001489,...,-0.060208,0.025102,-0.028676,-0.050481,-0.080664,-0.005889,0.031151,-0.041591,0.112407,1.0
401,0.15,0.00,0.41,0.29,0.15,0.158093,0.169786,-0.029671,-0.198965,-0.099228,...,-0.143651,0.185668,0.070702,0.242586,0.012573,0.142550,-0.009317,0.015927,0.110784,1.0
426,0.11,0.19,0.38,0.18,0.14,0.042017,-0.160993,0.134000,0.145635,0.080637,...,0.045438,0.181946,0.228217,0.062856,0.003738,0.012954,-0.001947,-0.011951,0.005164,1.0
439,0.35,0.07,0.18,0.30,0.10,0.097012,0.191439,0.181795,0.319439,-0.490435,...,-0.068087,0.143790,0.028749,-0.025147,-0.153267,-0.112117,0.175905,-0.087145,-0.020151,1.0
444,0.05,0.13,0.50,0.20,0.12,0.007545,0.044988,0.048166,-0.058198,-0.044270,...,0.119818,-0.077885,-0.027075,-0.050249,0.114882,-0.002323,0.164953,0.079850,-0.133372,1.0
446,0.11,0.00,0.50,0.29,0.10,0.292895,-0.073460,0.063280,-0.019684,-0.217238,...,-0.148797,0.063691,-0.106798,-0.178456,-0.013267,0.099299,0.034421,0.159125,0.037923,1.0
463,0.50,0.20,0.00,0.18,0.12,1.435891,0.060037,0.517319,-0.071703,-0.123645,...,0.152777,0.035623,-0.041314,-0.259989,0.030657,0.116892,-0.230637,0.016735,-0.010917,1.0
468,0.27,0.09,0.30,0.19,0.15,-0.303296,-0.191111,0.097418,0.390368,0.008876,...,-0.090609,-0.043120,0.045849,-0.121688,-0.079215,-0.336592,-0.193259,-0.041746,0.041916,1.0
473,0.10,0.09,0.50,0.21,0.10,-0.167260,0.134666,0.063463,-0.172754,0.232896,...,-0.094935,0.143790,0.163012,0.022454,-0.125839,0.027535,0.079272,-0.118735,-0.079369,1.0
484,0.50,0.18,0.00,0.22,0.10,0.477850,0.472999,-0.421105,-0.048855,0.193257,...,-0.023571,-0.116933,0.017631,-0.099503,0.060003,-0.054686,-0.154634,-0.141311,-0.311979,1.0
496,0.19,0.47,0.03,0.23,0.08,-0.247976,0.098255,-0.284162,-0.018565,-0.167694,...,-0.015927,0.115032,0.017782,-0.053473,-0.099212,-0.099912,0.082861,0.029386,-0.132658,1.0
498,0.03,0.04,0.42,0.42,0.09,-0.023764,0.027593,-0.013565,-0.009329,-0.064506,...,0.114583,-0.110158,-0.107278,-0.115154,0.009203,-0.107608,0.158314,-0.172139,-0.069779,1.0

In [71]:
test_df['Total_Fraction'].sum()

np.float64(500.0)

In [72]:
test_df.drop('Total_Fraction',axis=1,inplace=True)

In [73]:
test_df.shape

(500, 55)

In [74]:
create_features(test_df)

,Component1_fraction,Component2_fraction,Component3_fraction,Component4_fraction,Component5_fraction,Fraction1_Property1,Fraction1_Property2,Fraction1_Property3,Fraction1_Property4,Fraction1_Property5,...,mean_prop_6,std_prop_6,mean_prop_7,std_prop_7,mean_prop_8,std_prop_8,mean_prop_9,std_prop_9,mean_prop_10,std_prop_10
0,0.18,0.05,0.32,0.37,0.08,-0.032005,0.164909,0.131291,-0.103497,-0.047451,...,0.096057,0.134024,-0.122266,0.161029,0.024585,0.210149,0.001445,0.065744,-0.001974,0.144709
1,0.00,0.50,0.00,0.37,0.13,0.000000,-0.000000,0.000000,0.000000,0.000000,...,0.093562,0.140289,0.209866,0.235982,0.005654,0.055461,-0.207142,0.340287,0.084683,0.244310
2,0.16,0.00,0.17,0.50,0.17,0.247572,-0.058954,-0.048088,-0.211417,0.275041,...,0.093695,0.221982,-0.103845,0.145106,0.108027,0.121669,-0.091437,0.250785,-0.047302,0.229438
3,0.50,0.00,0.17,0.16,0.17,-0.212214,0.105448,0.082148,-1.104946,0.280700,...,-0.128845,0.244198,-0.021160,0.102016,0.295576,0.686814,-0.106691,0.110991,-0.024404,0.208326
4,0.00,0.00,0.50,0.50,0.00,-0.000000,0.000000,0.000000,0.000000,0.000000,...,-0.004113,0.428933,0.000401,0.167355,-0.115311,0.620673,-0.024116,0.129904,-0.037452,0.416008
5,0.29,0.21,0.00,0.50,0.00,-0.162925,0.048799,0.481715,0.009947,0.116949,...,-0.107469,0.229299,0.241617,0.334800,0.263015,0.305863,0.023693,0.097644,-0.065159,0.231581
6,0.28,0.17,0.04,0.37,0.14,0.246997,0.301877,0.302128,0.396296,-0.004451,...,0.095603,0.141571,0.026699,0.227563,0.076058,0.111498,0.018563,0.220355,-0.145421,0.323735
7,0.08,0.14,0.25,0.31,0.22,0.170444,0.061830,-0.053651,0.026709,-0.122361,...,0.089420,0.265424,0.092871,0.156289,0.001784,0.250611,-0.040141,0.115824,-0.023586,0.288817
8,0.09,0.13,0.25,0.32,0.21,0.125428,-0.121630,-0.184923,0.099049,0.132377,...,-0.043224,0.274193,0.078120,0.415572,-0.110526,0.136239,0.136200,0.183229,0.049273,0.067701
9,0.16,0.43,0.03,0.24,0.14,0.083611,-0.113094,0.287001,-0.199231,-0.061808,...,0.019105,0.182812,-0.092675,0.567260,0.217175,0.308006,0.131691,0.296281,-0.060169,0.412612
10,0.17,0.00,0.30,0.46,0.07,-0.100649,0.110654,-0.026759,-0.118463,0.032397,...,-0.076235,0.287611,-0.097804,0.280169,-0.092519,0.264976,-0.159963,0.183730,0.029203,0.085077
11,0.20,0.00,0.25,0.50,0.05,0.202027,-0.223730,0.176304,0.204877,-0.138792,...,0.070833,0.134710,-0.029111,0.147770,0.066406,0.194803,0.000709,0.022349,-0.034352,0.187866
12,0.00,0.13,0.25,0.50,0.12,-0.000000,0.000000,-0.000000,-0.000000,-0.000000,...,0.311794,0.292094,-0.052194,0.198356,0.022362,0.124558,0.113333,0.354248,0.061547,0.098407
13,0.40,0.00,0.20,0.33,0.07,0.610388,0.327643,-0.192641,-0.410747,0.738994,...,-0.050253,0.110492,-0.006458,0.251973,-0.007140,0.266751,-0.094620,0.379360,0.019180,0.153820
14,0.10,0.07,0.46,0.14,0.23,-0.042838,-0.021076,0.164862,-0.031604,0.007606,...,-0.161466,0.402887,-0.051676,0.066808,-0.044753,0.147986,-0.065348,0.159284,-0.030443,0.056849
15,0.35,0.14,0.04,0.37,0.10,0.160779,0.155520,-0.030478,0.017336,-0.372526,...,-0.169845,0.396892,0.282044,0.323751,0.030963,0.152986,-0.180502,0.310888,-0.025764,0.133400
16,0.14,0.23,0.31,0.28,0.04,-0.062617,-0.114288,0.120200,-0.030029,0.106389,...,0.094195,0.093839,0.025833,0.182757,-0.050380,0.062970,0.109565,0.084621,-0.006940,0.202421
17,0.50,0.06,0.10,0.18,0.16,-0.515987,-0.054065,-0.140051,-0.013314,0.666891,...,-0.048689,0.083293,0.047717,0.137403,0.149563,0.149005,0.105892,0.363023,-0.051234,0.157053
18,0.00,0.00,0.50,0.50,0.00,0.000000,-0.000000,-0.000000,-0.000000,0.000000,...,-0.195890,0.406106,-0.135907,0.186285,0.197125,0.271680,-0.137784,0.298396,0.181694,0.375622
19,0.50,0.06,0.13,0.25,0.06,-0.247208,-0.576210,-0.376216,-0.815537,-0.151253,...,-0.035036,0.144287,0.078033,0.089866,0.084852,0.137039,-0.073678,0.162475,-0.093958,0.580072
20,0.50,0.00,0.00,0.50,0.00,0.724720,-0.122100,-0.288932,0.037460,0.191860,...,-0.215006,0.294877,-0.026176,0.165031,0.218003,0.503604,0.095833,0.131230,0.085717,0.127467
21,0.34,0.00,0.00,0.50,0.16,-0.482693,0.197341,-0.108123,0.291323,-0.104094,...,0.179705,0.247201,-0.083315,0.262232,-0.080979,0.180206,-0.122833,0.288490,-0.128377,0.233289
22,0.17,0.00,0.27,0.41,0.15,0.123733,0.060656,0.130441,-0.114147,-0.007633,...,-0.106785,0.212645,0.061486,0.217508,-0.098828,0.196513,0.068816,0.156146,0.095171,0.242051
23,0.27,0.12,0.13,0.36,0.12,-0.519224,0.246567,0.479736,-0.060654,-0.694253,...,0.019486,0.091364,-0.069049,0.105665,-0.124459,0.407753,0.039985,0.251417,-0.141144,0.109532
24,0.04,0.21,0.25,0.50,0.00,0.024068,-0.032352,-0.037419,-0.033357,-0.000241,...,0.086499,0.256749,-0.187285,0.290356,-0.099248,0.069100,0.081647,0.294774,-0.051588,0.275442
25,0.05,0.16,0.49,0.20,0.10,-0.024017,0.019463,-0.045228,0.066959,-0.021979,...,0.036921,0.098362,0.109206,0.233465,-0.250442,0.213480,0.006230,0.165862,-0.086008,0.324918
26,0.09,0.28,0.27,0.12,0.24,0.062084,0.013344,0.017929,0.086254,0.063211,...,-0.062903,0.083592,0.102783,0.160847,-0.042969,0.205693,0.072329,0.051590,-0.054758,0.279506
27,0.12,0.16,0.17,0.50,0.05,0.005977,-0.041029,0.069213,-0.008070,-0.019620,...,-0.041009,0.157353,-0.212943,0.189800,-0.199739,0.191587,0.132068,0.312703,0.010551,0.152568
28,0.00,0.22,0.28,0.50,0.00,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.018328,0.165799,-0.187892,0.417567,-0.084645,0.282741,0.008831,0.180139,-0.099063,0.234668
29,0.10,0.37,0.22,0.13,0.18,-0.033481,0.177192,-0.036789,-0.028557,0.063918,...,0.038161,0.105510,0.063374,0.229008,-0.069177,0.165756,-0.021651,0.090897,-0.103307,0.336513
30,0.50,0.00,0.00,0.50,0.00,-0.367680,0.206106,-0.925854,0.311637,-0.405634,...,-0.031014,0.316193,-0.151258,0.346581,0.028837,0.076494,-0.066419,0.642744,-0.009425,0.089990
31,0.18,0.19,0.13,0.50,0.00,0.049625,0.186864,-0.064962,-0.243327,-0.011872,...,-0.104381,0.365249,-0.135525,0.301744,0.079256,0.336573,0.010848,0.080710,-0.036434,0.200439
32,0.29,0.24,0.02,0.24,0.21,-0.153940,-0.234078,0.333602,0.528244,-0.181622,...,-0.116418,0.443283,0.005490,0.142758,-0.010463,0.204760,-0.021932,0.227574,-0.026558,0.111198
33,0.19,0.05,0.36,0.26,0.14,-0.081720,0.489915,-0.169781,0.200422,-0.175286,...,-0.066717,0.178726,-0.122333,0.261156,0.111378,0.189267,-0.028794,0.068449,-0.058202,0.211722
34,0.00,0.20,0.30,0.50,0.00,-0.000000,-0.000000,0.000000,-0.000000,-0.000000,...,0.016494,0.077519,-0.195275,0.200340,-0.188175,0.190249,-0.235561,0.464217,-0.029512,0.159398
35,0.32,0.00,0.15,0.37,0.16,0.421952,-0.540635,0.621405,-0.365967,-0.397315,...,-0.045567,0.152879,-0.066364,0.117695,0.043863,0.351165,-0.074973,0.232612,-0.307375,0.429531
36,0.32,0.18,0.06,0.28,0.16,-0.703302,-0.064609,0.231970,-0.002022,0.054795,...,0.040109,0.088840,-0.111951,0.144230,-0.014851,0.292945,0.180083,0.211818,-0.074894,0.157239
37,0.00,0.16,0.43,0.26,0.15,0.000000,-0.000000,-0.000000,0.000000,-0.000000,...,0.043991,0.202232,0.035011,0.135877,-0.061654,0.150164,0.060055,0.178663,-0.088748,0.282956
38,0.23,0.29,0.00,0.48,0.00,-0.023861,-0.078789,0.071514,0.037084,-0.149530,...,0.193239,0.207488,0.098634,0.224288,-0.094700,0.247161,0.061475,0.159145,0.111586,0.198022
39,0.00,0.13,0.49,0.27,0.11,0.000000,-0.000000,0.000000,-0.000000,0.000000,...,-0.012138,0.043903,0.022836,0.236740,-0.094107,0.273020,0.153627,0.324110,0.033642,0.258707
40,0.08,0.00,0.32,0.43,0.17,0.049439,-0.069977,0.034930,-0.015941,0.104829,...,0.154608,0.167553,0.012043,0.074665,0.022650,0.476745,-0.126920,0.430854,0.072001,0.181213
41,0.24,0.05,0.04,0.50,0.17,0.052333,-0.333081,-0.208953,-0.374398,0.279321,...,-0.039281,0.190217,0.064059,0.111989,-0.005070,0.179250,0.013487,0.057581,0.058636,0.190787
42,0.00,0.39,0.30,0.27,0.04,-0.000000,0.000000,0.000000,-0.000000,0.000000,...,0.102324,0.125648,-0.071782,0.088290,-0.070310,0.429552,-0.075471,0.269755,-0.023810,0.134736
43,0.34,0.05,0.13,0.27,0.21,-0.421294,0.145280,0.668382,-0.104000,0.137186,...,-0.050008,0.097366,-0.039125,0.184753,0.193013,0.185557,-0.149499,0.148621,-0.073512,0.178536
44,0.50,0.00,0.00,0.50,0.00,0.156487,0.415620,-0.740812,-0.279875,0.186597,...,-0.117147,0.177467,-0.243361,0.518582,0.038741,0.221990,0.047310,0.443547,0.116227,0.408767
45,0.50,0.10,0.07,0.07,0.26,-0.447357,0.490376,0.142748,-0.625136,0.660875,...,0.022486,0.098923,0.170584,0.342426,-0.028864,0.093553,0.069987,0.158760,-0.015459,0.122704
46,0.10,0.35,0.05,0.50,0.00,-0.070425,0.036106,0.040221,-0.061052,0.018499,...,-0.182103,0.324672,-0.121904,0.489783,-0.067466,0.216523,-0.117352,0.705454,-0.229878,0.379187
47,0.10,0.40,0.07,0.26,0.17,0.039950,0.005974,0.033587,0.053696,0.014481,...,-0.063245,0.137787,0.204942,0.305489,0.081720,0.096058,0.157695,0.271996,0.064301,0.285255
48,0.27,0.03,0.25,0.37,0.08,0.066306,-0.439960,0.205017,-0.495225,0.023784,...,-0.115581,0.146958,-0.059628,0.266651,-0.133760,0.150626,-0.167041,0.334086,0.015554,0.227343
49,0.07,0.49,0.12,0.25,0.07,-0.034454,0.085751,-0.140163,0.040430,-0.025627,...,-0.034179,0.352712,-0.116323,0.130234,-0.112043,0.176817,-0.086039,0.122889,-0.071835,0.113720
50,0.00,0.00,0.38,0.50,0.12,-0.000000,-0.000000,0.000000,-0.000000,0.000000,...,-0.345433,0.529819,0.172028,0.235925,-0.346219,0.531388,-0.173962,0.215070,0.024812,0.128974
51,0.17,0.00,0.50,0.18,0.15,-0.082183,0.038360,0.258389,-0.078758,-0.148069,...,0.064301,0.205213,0.165089,0.636466,-0.113358,0.383961,0.187654,0.449133,-0.020720,0.108695
52,0.09,0.30,0.09,0.39,0.13,0.031289,0.135157,0.004732,-0.090590,0.036585,...,-0.120284,0.214209,-0.058537,0.400642,0.171238,0.493488,-0.000500,0.105028,-0.020294,0.249238
53,0.05,0.12,0.22,0.47,0.14,0.010452,-0.046276,-0.056724,-0.007678,0.000301,...,-0.172502,0.337441,-0.046828,0.142444,0.000792,0.184834,-0.236055,0.474900,0.400658,0.503242
54,0.11,0.18,0.28,0.31,0.12,0.060049,-0.080313,-0.038657,-0.073860,0.112093,...,0.200473,0.253630,0.056888,0.258957,0.062388,0.203096,0.147455,0.117410,-0.143104,0.146539
55,0.00,0.22,0.37,0.26,0.15,0.000000,-0.000000,-0.000000,0.000000,0.000000,...,0.041279,0.122953,0.075854,0.101563,0.141610,0.229924,0.000134,0.131659,-0.239850,0.157294
56,0.08,0.11,0.25,0.49,0.07,0.081838,-0.046763,-0.018418,0.172937,0.032038,...,0.157920,0.208606,0.003388,0.175612,-0.002329,0.213962,0.075844,0.205989,-0.017276,0.232661
57,0.50,0.00,0.00,0.50,0.00,-0.357188,0.385455,0.688395,0.448726,-0.265445,...,-0.023198,0.373774,0.011176,0.102421,0.004809,0.324009,-0.281856,0.410467,-0.143058,0.291731
58,0.08,0.18,0.44,0.15,0.15,-0.045320,-0.071052,0.015019,0.078295,0.006755,...,-0.171259,0.202383,0.039560,0.089083,-0.044223,0.193247,-0.031027,0.146519,-0.205263,0.365166
59,0.50,0.00,0.00,0.50,0.00,-0.116675,-0.159150,0.472430,-0.653061,0.246862,...,-0.048500,0.355108,-0.180641,0.257328,-0.111463,0.158819,0.054461,0.117873,0.140798,0.228133
60,0.09,0.50,0.06,0.15,0.20,-0.045253,0.039843,-0.023773,0.061121,0.095502,...,-0.117342,0.164212,-0.031572,0.205754,0.087182,0.083263,-0.120818,0.102631,0.066020,0.213710
61,0.50,0.17,0.00,0.16,0.17,0.220858,-0.609654,0.310831,0.073001,-0.267808,...,0.213424,0.420215,0.154795,0.294839,-0.093259,0.233161,-0.088447,0.280857,0.190774,0.125244
62,0.21,0.11,0.07,0.42,0.19,0.468905,0.306279,0.164590,-0.107951,-0.171539,...,0.068896,0.232176,-0.044766,0.309391,0.008219,0.149091,0.022594,0.071869,-0.123828,0.181723
63,0.49,0.00,0.12,0.30,0.09,0.165998,-0.186492,0.173130,-0.281741,-0.433420,...,-0.296091,0.567189,0.008680,0.144092,-0.018288,0.193898,-0.080189,0.093763,0.034549,0.195594
64,0.10,0.04,0.50,0.33,0.03,0.077882,-0.127439,-0.088311,0.055219,0.067097,...,0.219470,0.320295,0.025788,0.280564,0.062737,0.266801,0.225093,0.412743,-0.095162,0.228577
65,0.48,0.07,0.00,0.33,0.12,0.393503,1.104221,-0.208905,-0.775604,0.284735,...,0.024354,0.223940,-0.229761,0.274963,-0.098825,0.240954,0.007327,0.296911,-0.026614,0.238759
66,0.29,0.07,0.08,0.36,0.20,0.062519,0.275100,0.045910,-0.502460,-0.319319,...,0.056922,0.150647,0.081998,0.142126,0.118428,0.355593,-0.043170,0.239903,-0.144763,0.257855
67,0.00,0.38,0.26,0.21,0.15,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.088133,0.236799,-0.057494,0.136094,0.079447,0.376919,0.007287,0.184613,0.179718,0.494528
68,0.00,0.14,0.22,0.50,0.14,0.000000,0.000000,-0.000000,-0.000000,0.000000,...,-0.140376,0.235504,0.092302,0.222879,0.029608,0.102253,-0.007420,0.124471,-0.046617,0.153899
69,0.30,0.11,0.05,0.49,0.05,0.130997,0.217306,0.087444,0.494670,0.011473,...,-0.084461,0.184719,-0.010104,0.077190,-0.066829,0.112531,0.172082,0.271748,-0.015612,0.052364
70,0.17,0.21,0.07,0.50,0.05,-0.229155,-0.167094,0.126286,0.409786,0.015925,...,0.001877,0.217795,-0.047138,0.163213,0.062547,0.151518,0.007857,0.056906,0.059276,0.242774
71,0.00,0.19,0.50,0.14,0.17,-0.000000,-0.000000,0.000000,0.000000,-0.000000,...,0.076479,0.165617,0.062358,0.082008,-0.100478,0.162133,0.036983,0.106272,0.021770,0.132336
72,0.00,0.00,0.45,0.49,0.06,0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,0.183175,0.376488,0.152539,0.209643,-0.102112,0.120500,0.086342,0.175250,0.057274,0.260511
73,0.17,0.00,0.17,0.50,0.16,0.057360,-0.017434,-0.097983,-0.102063,0.000694,...,-0.156003,0.111827,-0.061128,0.157074,-0.050235,0.208648,-0.011786,0.136987,0.046917,0.093477
74,0.02,0.26,0.23,0.30,0.19,0.035612,-0.001651,-0.020944,-0.008352,0.000855,...,-0.065006,0.230041,0.069557,0.203519,0.025350,0.252935,-0.031555,0.174387,-0.013369,0.232426
75,0.43,0.17,0.10,0.12,0.18,-0.402933,-0.507948,-0.418555,0.073697,-0.513290,...,0.023264,0.188526,0.068680,0.174390,-0.242278,0.394044,0.168260,0.230728,0.066117,0.108011
76,0.27,0.12,0.24,0.28,0.09,-0.250838,0.349346,0.115060,-0.221048,0.226468,...,-0.022856,0.126616,0.049811,0.106246,-0.089551,0.196094,0.079150,0.243051,-0.072596,0.185409
77,0.11,0.00,0.50,0.23,0.16,-0.018757,-0.105631,-0.223549,-0.091732,-0.098220,...,0.188217,0.308676,-0.087293,0.136727,0.096847,0.169224,0.063210,0.253781,-0.061938,0.258509
78,0.31,0.06,0.14,0.28,0.21,-0.502321,-0.088509,-0.221503,-0.324625,0.459895,...,-0.073051,0.183945,-0.071769,0.208400,-0.044865,0.074769,0.032874,0.183024,-0.199003,0.283863
79,0.00,0.42,0.00,0.38,0.20,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,0.075593,0.203606,0.008709,0.199967,0.113450,0.498899,0.048585,0.108147,-0.100660,0.127747
80,0.08,0.12,0.21,0.50,0.09,-0.026696,-0.052140,-0.028034,-0.001724,-0.032021,...,-0.160220,0.313540,0.129687,0.129786,0.139467,0.357039,-0.044832,0.093127,-0.014818,0.130552
81,0.04,0.08,0.50,0.24,0.14,0.030452,0.000134,-0.002266,0.102513,0.010648,...,0.068494,0.347051,-0.002063,0.143560,-0.085817,0.224947,0.075879,0.283947,-0.004047,0.138461
82,0.17,0.07,0.31,0.45,0.00,0.066048,0.091090,0.340974,-0.108105,0.210891,...,0.028226,0.173459,-0.126050,0.174706,0.008780,0.148346,0.073804,0.238447,-0.112414,0.560292
83,0.14,0.04,0.37,0.25,0.20,-0.101240,-0.036483,0.204691,-0.266735,-0.005023,...,0.077907,0.320701,0.054379,0.129257,-0.008680,0.265625,-0.096174,0.218659,0.008610,0.217669
84,0.04,0.50,0.00,0.37,0.09,0.067581,0.001485,-0.020441,0.005637,0.077105,...,-0.203583,0.312971,-0.093146,0.129303,0.172941,0.278119,-0.167851,0.233098,0.101837,0.149514
85,0.50,0.00,0.00,0.50,0.00,1.179208,0.190860,0.311080,0.415723,-0.330115,...,0.157681,0.540689,0.159203,0.218013,0.161161,0.236643,-0.300135,0.469770,0.140520,0.282942
86,0.50,0.06,0.09,0.27,0.08,-0.273931,0.344307,-0.588440,-0.381422,0.417881,...,0.195147,0.274849,0.165291,0.283495,-0.085221,0.210003,0.013325,0.031490,-0.183798,0.265864
87,0.50,0.01,0.11,0.27,0.11,-0.921101,-0.065213,0.622060,-0.246872,0.268669,...,-0.125734,0.341332,0.001307,0.078227,-0.020509,0.134828,-0.122156,0.294253,-0.063970,0.184155
88,0.06,0.15,0.45,0.31,0.03,-0.017993,-0.079041,-0.180022,-0.011346,0.025769,...,-0.078284,0.104455,-0.075732,0.205849,-0.107814,0.214871,-0.010299,0.096866,0.061718,0.206949
89,0.50,0.00,0.00,0.41,0.09,0.050148,-0.271776,-0.117856,-1.531445,0.464396,...,-0.133227,0.200792,0.074012,0.242931,-0.039457,0.304279,-0.056437,0.250932,0.159997,0.315562
90,0.50,0.16,0.00,0.15,0.19,0.119950,-0.752772,-0.339058,-0.170712,0.447530,...,0.028172,0.338585,0.100548,0.281493,-0.034484,0.166665,-0.029897,0.231777,-0.149517,0.160158
91,0.15,0.23,0.23,0.36,0.03,-0.230172,0.188917,-0.146905,-0.110619,0.150083,...,0.000645,0.081053,0.114829,0.169448,-0.011388,0.584698,-0.082913,0.077141,0.161923,0.521323
92,0.50,0.00,0.00,0.39,0.11,0.243879,-0.670803,0.472680,0.428416,-0.727907,...,0.015745,0.233095,0.303888,0.480352,0.083869,0.185215,0.000138,0.061430,0.096480,0.289393
93,0.08,0.07,0.22,0.50,0.13,-0.052321,0.061988,0.049494,-0.030970,0.149964,...,-0.033109,0.076678,-0.135420,0.259278,-0.017847,0.275534,0.085256,0.113551,0.055756,0.339494
94,0.27,0.25,0.17,0.03,0.28,0.266271,-0.364270,-0.179186,-0.044203,0.024770,...,0.083720,0.118499,0.019177,0.178134,0.172220,0.240058,0.060197,0.258131,0.144152,0.196511
95,0.31,0.09,0.13,0.47,0.00,-0.497079,0.072899,0.123447,-0.415916,0.734366,...,-0.213668,0.337669,-0.104893,0.303295,0.026295,0.136019,-0.104837,0.222294,-0.049740,0.238904
96,0.24,0.04,0.36,0.27,0.09,0.546468,-0.152879,0.109577,-0.251323,0.151185,...,-0.041039,0.061015,-0.077317,0.235784,-0.100186,0.198416,0.147386,0.323309,-0.031384,0.159634
97,0.14,0.16,0.20,0.50,0.00,-0.033101,-0.172539,0.024328,-0.125991,-0.016513,...,-0.143661,0.153362,0.069000,0.233807,0.015012,0.478690,0.107815,0.192376,-0.026755,0.201536
98,0.15,0.50,0.00,0.15,0.20,-0.397883,-0.112370,-0.085707,-0.216482,0.324819,...,-0.190364,0.286481,0.013686,0.085279,0.094840,0.191335,0.016228,0.132432,0.355736,0.552363
99,0.18,0.14,0.26,0.33,0.09,0.326443,-0.018991,-0.080853,0.120415,0.172945,...,-0.052325,0.137415,-0.175943,0.228408,0.023740,0.135741,-0.080411,0.138872,-0.097585,0.128075
100,0.00,0.50,0.00,0.50,0.00,0.000000,-0.000000,0.000000,-0.000000,-0.000000,...,0.140223,0.198862,-0.012952,0.056574,-0.116555,0.161897,0.065541,0.091764,-0.135098,0.256739
101,0.19,0.26,0.05,0.43,0.07,-0.123935,0.233626,-0.293354,-0.218258,-0.025431,...,0.100293,0.122851,0.024414,0.117735,0.022264,0.057891,0.113468,0.193719,-0.007410,0.313485
102,0.08,0.50,0.07,0.28,0.07,0.094576,-0.088390,-0.092435,-0.043968,-0.138156,...,-0.006775,0.075099,0.104032,0.327359,-0.021143,0.075558,0.202432,0.478405,0.056522,0.174714
103,0.40,0.00,0.12,0.48,0.00,-0.798796,-0.233028,-0.023062,0.690025,-0.451869,...,0.059088,0.196758,0.110373,0.147977,-0.181684,0.660434,0.254182,0.342252,0.024538,0.464056
104,0.30,0.04,0.10,0.47,0.09,0.355735,0.197436,0.166897,-0.099381,-0.166937,...,-0.003618,0.257120,0.180327,0.338722,0.070260,0.279009,-0.138227,0.233304,-0.287350,0.349653
105,0.00,0.50,0.10,0.14,0.26,-0.000000,-0.000000,0.000000,-0.000000,-0.000000,...,0.067699,0.105775,-0.170343,0.278208,0.218794,0.233913,-0.165249,0.290830,0.004133,0.320410
106,0.09,0.20,0.39,0.27,0.05,-0.003316,0.141974,-0.125940,0.160739,0.005279,...,0.015677,0.075254,0.051211,0.328653,0.048424,0.147713,-0.016198,0.404083,-0.039492,0.061318
107,0.11,0.09,0.31,0.47,0.02,0.000129,-0.044426,-0.027300,-0.063248,0.054050,...,0.079606,0.227412,-0.154678,0.146588,-0.072667,0.126826,-0.087982,0.239164,-0.126327,0.175059
108,0.22,0.02,0.22,0.50,0.04,0.207566,0.278738,-0.437990,-0.084049,-0.137451,...,-0.070168,0.166407,-0.035828,0.191282,0.012725,0.137717,-0.202694,0.349235,0.070560,0.178916
109,0.00,0.36,0.24,0.18,0.22,-0.000000,-0.000000,0.000000,-0.000000,-0.000000,...,0.017385,0.148971,-0.088977,0.189774,-0.077992,0.318190,-0.034285,0.375207,-0.009190,0.190351
110,0.14,0.00,0.29,0.50,0.07,0.012538,-0.115298,0.263834,0.269942,-0.084130,...,-0.117750,0.100736,0.095952,0.189364,0.012164,0.039395,0.062480,0.145504,0.004326,0.105512
111,0.28,0.04,0.06,0.50,0.12,-0.324448,0.585557,0.083011,-0.301740,-0.208025,...,-0.040700,0.085548,-0.135427,0.153237,0.018989,0.086444,0.131638,0.257973,-0.197393,0.262025
112,0.28,0.18,0.16,0.24,0.14,0.024557,-0.244826,-0.108035,0.153192,-0.290922,...,-0.052182,0.133080,-0.016548,0.228967,-0.034752,0.129892,0.023550,0.302973,0.097103,0.108448
113,0.00,0.38,0.14,0.40,0.08,0.000000,-0.000000,-0.000000,0.000000,0.000000,...,0.081504,0.128570,-0.016386,0.261185,-0.188037,0.149109,-0.045208,0.322618,0.023870,0.226294

In [75]:
test_df.shape

(500, 78)

In [77]:
#test_df = test_df[abs(test_df['Total_Fraction'] - 1) < 1e-6]  # Using 1e-6 tolerance

In [78]:
#print(f"Rows remaining: {len(test_df)}")

In [79]:
test_df.shape

(500, 78)

## Saving Test file

In [80]:
!pwd

/home/pkn/workspace/side_projects/he_shellai_2025/notebooks

In [81]:
processed_folder = "../data/processed/"

In [82]:
test_df.to_csv(processed_folder+"processed_test.csv",index=False)

# Improvements to be implemented in future

* the target columns should be removed in the data exploration itself to avoid the data leakage.